eclipse-windowbuilder/windowbuilder

- org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite2.java
Looks like the "canUseAwt" should only be performed on Mac system, so I skip it if the system is not Mac.
> Bug 560900 - Border preview function not works.

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/menu/MenuInfo.java
Problem on windows : the menu image is created by a native call, and we have to call readAndDispatch in order to get a correct image
> Bug 566878 - [Design] Incorrect Menu items display after modification

- org.eclipse.wb.core.ui/plugin.xml
The source page now uses "Java Font" defined in the preferences of Eclipse (instead of using Basic > Text Font)
> Bug 526365 - Source pane font doesn't follow "Text font" setting

- org.eclipse.wb.core.feature_feature/build.properties
- org.eclipse.wb.core.feature_feature/p2.inf
Add the VM argument "--illegal-access=permit" to "eclipse.ini" via the
separate fragment "org.eclipse.wb.illegal_access_permit" and the p2
Eclipse touchpoint action "addJvmArg"
(<https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/guide/p2_actions_touchpoints.html>)
as workaround for bug 572210
(<https://bugs.eclipse.org/bugs/show_bug.cgi?id=572210>).
> Bug 572210 - In eclipse.ini, add the VM argument --illegal-access=permit

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/JFaceTests.java
e41ae02aff23f3ba599472c47ac4832ce29b3c06 removed the test but it was
still referred too in the test suite
> Also remove TableTreeTest from Test suite

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/DesignerPluginTest.java
prevention
https://github.com/eclipse/windowbuilder/issues/42 removed the security
manager, but we left the corresponding test included.
For #42
> Removes exit test which test the removed security manager exit

- org.eclipse.wb.core.ui/META-INF/MANIFEST.MF
org.eclipse.wb.core.ui
Latest Eclipse release reports this as error.
> Fixes PDE error for non-existing package export in

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/geometry/Rectangle.java
Having a negative width or height value of the Rectangle, produces an
error and makes no sense. This negative value occurs when a border has
been set however the rectangle has only a height or width of 1. If this
is the case then the crop method tries to reduce the width/height of the
rectangle by the width/height of the Insets. This can potentially reduce
the height/width of the rectangle to a negative value and this leads to
an error.
Closes Issue #162
> Adjusting crop method to prevent negative height and width values

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ui/dialogs/image/pages/browse/classpath/ClasspathImageRoot.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/editor/constants/IEditorPreferenceConstants.java
Instead of listing all the resources in the available classpaths
A specific jar name can now be specified. This will be the only jar
displayed in the classpath list of the icon image chooser. This was
added to avoid clients using the wrong classpaths by limiting their
options to only that of a specific icon pack jar
> Specify a specific jar name to be used as icon pack

- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/AbstractEditPartViewer.java
This is to avoid the error message that is logged whenever a button is
"pasted" in a location it cannot be pasted. For example pasting it on top of another button
> Replaced Assert.isNotNull with "if" nullcheck

- org.eclipse.wb.core/src/org/eclipse/wb/core/editor/constants/IEditorPreferenceConstants.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gefTree/part/ObjectEditPart.java
This commit will allow a default name to be set (other than the fully qualified name) for the Root object in the Objects Tree view.
> Root object display name

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/DesignComposite.java
We need the possibility of obtaining this GraphicalViewer object in our
code. This is so we can use it in our own application specific drag and
drop implementation.
> Adding a public getViewer method

- org.eclipse.wb.rcp.nebula/src/org/eclipse/wb/internal/rcp/nebula/gef/EditPartFactory.java
> Code cleanup run to add missing annotations org.eclipse.wb.rcp.nebula

- org.eclipse.wb.os.macosx/src/org/eclipse/wb/internal/os/macosx/OSSupportMacOSXCocoa.java
> Code cleanup run to add missing annotations org.eclipse.wb.os.macosx

- org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
> Code cleanup run to add missing annotations org.eclipse.wb.os.linux

- org.eclipse.wb.tests/pom.xml
> Document that org.eclipse.osgi.compatibility.state is required for

- .github/workflows/maven.yaml
Looking at the SWT build action from
https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/.github/workflows/maven.yml
it looks like we can update the WB GH build actions to a more flexible
setup.
> Update of Github build action

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/CoreTests.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/EnvironmentUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/WrapperInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ConstructorCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ExposedFieldCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/FactoryDescriptionHelperTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/generic/FlowContainerAbstractGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/generic/SimpleContainerAbstractGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/generic/SimpleContainerModelTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/EventsPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/StandardConvertersTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/util/TemplateUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/EditableSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/NlsSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/SourceEclipseOldTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/AstEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/BindingsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/jdt/core/JavaDocUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/jdt/core/ProjectUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/jdt/core/SubtypesScopeTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/reflect/ReflectionUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ui/ImageUtilsTest.java
Updating the SWT core tests so that less are failing.
Work includes:
- update of the reflection utils tests for the updated Java API
- Deletion of EnvironmentUtilsTest which pointed to specific developer
machines
- adding dispose calls for image tests to avoid non-disposed exceptions
- Using equals instead of same for test_getJavaProject
- disabling multiple tests via the DISABLED_ prefix
- fixes tests in StandardConvertersTest  which needs adjustments for
https://github.com/eclipse/windowbuilder/pull/229
- Also removes a bunch of <Java 8 tests in StandardConvertersTest
> SWT Core tests cleanup

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/models/spinner/NumberSpinnerComposite.java
After testing I found the real source where the Spinners Model is created, so this is the real fix for the issue
> Fix deprecated use of new Integer/Double etc in Code Generation #227

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/description/DescriptionVersionsProvidersTest.java
Without this change, the test code which is also zipped and used in the
tests does not depend anymore on Guava and that should allow to merge
https://github.com/eclipse/windowbuilder/pull/250
> Update DescriptionVersionsProvidersTest to not use Guava in test code

- org.eclipse.wb.tests/.classpath
Removes double entry in classpath if you press the "Update classpath"
button on the test MANIFEST.MF.
> Cleanup classpath in wb.tests

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/structure/property/ComponentsPropertiesPage.java
The visibility of Advanced Properties and Events Actions on the Components Properties Toolbar can now be set using the Windowbuilder basic UI preference
> Advanced properties basic UI

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/SwtResourceManager.java
Guavas Maps.newHashMap(); is just wrapper around new HashMap<>(); so
letts use this directly. This will reduce the number of classes loaded
by SWTResourceManager and may help with stabilizing the
SWTResourceManagerTest tests which are currently sometimes failing.
> Replacing Guava Maps with regular HashMap in SwtResourceManager.java

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/events/EventTable.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/EditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/requests/Request.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/AbstractEditPartViewer.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/CachingLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/model/ObjectInfo.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/model/broadcast/BroadcastSupport.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/BundleResourceProvider.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/DesignerPlugin.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/AbsoluteBasedLayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/snapping/IAbsoluteLayoutCommands.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/snapping/PlacementsSupport.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/Property.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/PropertyManager.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/presentation/ButtonPropertyEditorPresentationImpl.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/util/ScriptUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/GenericTypeResolver.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/external/ExternalFactoriesHelper.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/ReflectionUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/UiUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/views/AbstractExtractableDesignView.java
Guavas Maps.newHashMap(); is just wrapper around new HashMap<>(); so
letts use this directly. This will slightly reduce the complexity as we
have one library call less.
> Replacing Guava Maps with regular HashMap wb.core

- org.eclipse.wb.core.feature_feature/feature.xml
- org.eclipse.wb.core.java.feature_feature/feature.xml
**Problem:**
The [bundles that have the `type="Maven"` in the target platform](https://github.com/eclipse/windowbuilder/blob/fe1008e1dd67634a735efa7feef389fdcb2c1bfb/target-platform/wb.target#L12-L61) are currently missing in the [_lastgoodbuild_ update site](https://download.eclipse.org/windowbuilder/lastgoodbuild/) since they are not contained in any feature. This prevents an installation of WindowBuilder from the _lastgoodbuild_ update site.
**Solution:**
Add those bundles to the corresponding features.
> "lastgoodbuild" update site misses bundles from Maven Central

- pom.xml
- setups/WindowBuilder.setup
- target-platform/mvn/wb-mvn.target
- target-platform/wb.target
Split out from wb.target, the Maven locations into a separate a
wb-maven.target that can be included/composed into both the wb.target
and in the targlet task of the WindowBuilder.setup.
Tycho 2.7.3 can consume such a composed *.target and the targlet setup
avoids duplicating the resolution of the non-Maven content to the target
platform.
> Improve the target platform setup for better reuse

- org.eclipse.wb.jdt.fragment/.classpath
- org.eclipse.wb.jdt.fragment/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.wb.jdt.fragment/META-INF/MANIFEST.MF
As jdt.core is also on Java 11 we should adjust the fragment to use the
same (actually I don't think the BREE of the fragment is relevant, but
why challenge the setup and ask for undiscovered bugs).
> wb.jdt.fragment BREE has been updated to Java 11

- .github/workflows/unit-tests.yml
Wioth this action the PR should get the test results uploaded.
Copied and slightly adjusted from
https://raw.githubusercontent.com/eclipse-equinox/equinox/master/.github/workflows/unit-tests.yml
> GH action for publishing unit test results

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/DesignContextMenuProvider.java
Basic UI version of editor context menu created using the Basic WB UI preference.
Basic UI version of context editor contains only the Copy, paste, cut and delete option
Solution description: I have added preferences to the DesignContextMenuProvider class in the buildContextMenu method. These preferences are not available to the user but can be set by using the InstanceScope. The default for these preferences are set to true and therefore will always show all the actions as previously defined unless the developer incorporating windowbuilder into their product sets the preferences to false.
The two preferences are:
To hide the same actions as are found on the Windowbuilder toolbar, i.e. the Test and Refresh actions
To hide object specific actions that vary depending on which object the …
> Editor context menu basic UI

- .gitignore
https://github.com/eclipse/windowbuilder/pull/282 added target-plaform as module, so we should ignore the generated file for git.
> Ignore new polyglot.wb.target file

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/resource/ResourceManagerTest.java
ResourceManagerTest
The ResourceManagerTest assumed that the first test in the file is
executed as a first test as this would ensure that the ResourceManager
class is available in the test.
The waitForAutoBuild() checked for such cases but it was hard to see. So
by commenting assertEquals() at the end of this method out and by adding
he following code after the waitForAutoBuild() call in the test I could
use the runtime IDE after the failing situation to see what actually is
the case in Eclipse.
Display.getDefault().syncExec(() ->
{
while (true) {
Display.getDefault().readAndDispatch();
}
});
This way it was easy to see that the corresponding file was not present
the generated test code.
> Ensures that org.eclipse.wb.swt.ResourceManager is available for the

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/PaletteManager.java
- org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/UiMessages.java
- org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/UiMessages.properties
- org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/LayoutsPreferencePage.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/editor/constants/IEditorPreferenceConstants.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/preferences/bind/AbstractBindingPreferencesPage.java
- org.eclipse.wb.swing/plugin.xml
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/ContainerEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/ContainerInfo.java
- org.eclipse.wb.swing/templates/JFrame_advanced.jvt
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/part/CompositeEditPart.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/CompositeInfo.java
This closes issue #181 
Users are now able to set the specific layouts they want to be made available in Windowbuilder. By default all layouts are available.
Following is a screenshot of the preference page in Swing:
Following is a screenshot of the preference page in SWT:
Below the preferences are set to only include the border layout, the UI changes can be seen in the layout group on the designer palette as well as in the context menu and layout dropwdown in the Properties view.
> Set Layouts via Preference Page

- pom.xml
The tycho-gpg-plugin is used for that purpose.
https://github.com/eclipse/windowbuilder/issues/302
> Ensure that the direct-from-maven dependences are PGP signed

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalettePopupActions.java
Fixed missing elements from Designer Palette Context Menu by adding in old code that was removed during commit of new feature
https://github.com/eclipse/windowbuilder/discussions/319
> Fixes Discussion: #319 -Fixed missing elements from Designer Palette Context Menu

- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/CreatorManager.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/properties/ListPropertyCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/properties/ListPropertyDetailCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/properties/SetPropertyCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/properties/SetPropertyDetailCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/properties/ValuePropertyCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/properties/ValuePropertyDetailCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/WidgetsObserveTypeContainer.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/input/CellEditorValuePropertyCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/input/ViewerCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/input/ViewerInputParser.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/ViewerPropertyCheckedElementsCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/ViewerPropertyFiltersCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/ViewerPropertyMultiSelectionCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/ViewerPropertySingleSelectionCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/WidgetPropertiesCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/WidgetPropertyItemsCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/properties/WidgetPropertyTextCodeSupport.java
This PR updates the Properties class references to the new locations. It only implements a partial solution of the deprecated class databinding. For the properties files the replacement is quite simple, as the only change (wrt to windowbuilder) is the package renaming.
**Bound for separate PR** as the implementation substantially differs, and a drop-in-replacement is not easily possible:
- [ ] org.eclipse.core.databinding.beans.PojoObservables? -> reimplement required functions in ` org.eclipse.core.databinding.beans.typed.PojoProperties`
General info
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=546820
see https://git.eclipse.org/c/platform/eclipse.platform.ui.git/commit/?id=4f25fbf41f9411ded14d3cec0e951e7bcaf51319
> [1/2] Databinding binds to deprecated classes (Properties Classes) #323 

- .github/workflows/maven.yaml
Currently, the build job is aborted when at least one test has failed. As a result, none of the test results are uploaded to GitHub, and the developer has to either manually dig through the build log or retest them manually. With this change, the Maven build will ignore test failures and the pipeline instead fails after evaluating the test results.
> Upload test results, even on test failures.

- .github/workflows/maven.yaml
The xvfg-action by GabrielBB is no longer maintained as has been replaced by setub-xvfb. Furthermore, the old action is still using an old version of Node.js, which is announced to be deprecated by the summer of this year.
From the GitHub documentation:
Node 12 has been out of support since April 2022, as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.
To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. This will come into effect starting on September 27th.
> Update xvfb-action to a version which is using Node.js v16

- .github/workflows/maven.yaml
- .github/workflows/unit-tests.yml
The setup introduced with 3b9a81b
results in the false impression that everything works fine, even with our currently lots of unit test errors.
I suggest we have the verification build again if we have test errors so that we have to fix or disable the failing tests and make it easier for use to avoid changes which result in new failing test.
Test results are uploaded, regardless of test failures, so that they can be accessed by the "Publish Test Results" action. The fast-fail has been disabled, to ensure that test failures in one matrix job doesn't cancel the remaining, still running jobs. Lastly, the "Publish Test Results" action has been adapted to not only publish the results on success, but also on failure.
> Fail the verification build if we have test errors

- .github/workflows/maven.yaml
The property 'matrix.config.native' is not set on the build nodes. Therefore, the artifact name is e.g. 'test-results--java11' for the Java 11 builds, for both the Windows and Linux build. This means the that the test results that are uploaded first are overwritten by the ones that are uploaded last, meaning we only upload half the test results and miss out on potential test failures!
By using 'matrix.os', the same property used in the job matrix, we can ensure that it exists and - in combination with the Java version - is unique.
> The artifact name for the test results should be unique.

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/ExpandItemInfo.java
Those fields only exist in the win32 widgets, but not in the gtk widgets, leading to a NoSuchFieldError if trying to be used on Linux.
As far as I can tell, those coordinates are always set to 0, which are used instead, to determine the model bounds.
> Remove reflective access to x & y coordinates of ExpandItem widget.

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/property/IconPropertyEditorTest.java
The test fails because the image, that was created as part of the test, can't be properly deleted. Most likely because of the wonky nature of the Windows file system...
Use forceDeleteFile instead, which should properly handle the CoreException.
> Stabilize IconPropertyEditorTest on Windows builds

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/gbl/GridBagLayoutGefTest.java
When executing the entire test suite, the GridBagLayoutGefTest is executed before the ComponentsPropertiesPageTest. One of the side-effects of this test is that the shell, in this case the entire IDE, is set to invisible, after calling OSSupport.makeShot().
If a successive test case now opens the design page, the property table is not initialized, leading to this error.
> Fix NPE in ComponentsPropertiesPageTest.

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/ComponentInfo.java
Trying to fetch the screen location of the parent and child component sporadically results in broken coordinates. For example, (3855, 314) for the parent and (10030, 10029) for the child, even though (4350, 744) and (4525, 749) were expected. This leads to a new bound located somewhere outside of the design page.
> Fix invalid bounds of Swing components on Linux

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/generic/OpenListenerEditPolicyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/DesignerExceptionUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/AstEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/ApplicationWindowGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/ControlDecorationTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/CoolBarManagerTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/PageLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/util/SurroundSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/DialogTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/ExpandBarTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/TabFolderTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/AppletTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/ComponentTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/menu/JMenuBarTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/AbsoluteLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/MigLayout/MigLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/gbl/GridBagLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/layouts/AbsoluteLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuComplexTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuProblemsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/CompositeTopBoundsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/ControlTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/TableTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/TreeTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/TreeDragToolTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/TreeRobot.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/TreeToolTest.java
The boundary & coordinate checks of widgets have been modified to only check the width and height, as the x and y coordinates are platform-specific. Furthermore, widgets on Linux tend to be ~2px taller in each direction. Where appropriate, this has been taken into consideration.
Because the tests are run in the UI thread, it is sometimes necessary to explicitly execute other UI jobs, such as redrawing widgets, in order to properly execute tests that, for example, tests that select widgets based on their position in the design page.
> Adapt platform-sensitive checks to both work on Windows and Linux.

- org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
In case the size of a widget or composite is determined by its layout, rather than a fixed size, the layout() function has to be explicitly called. Otherwise they are drawn with an empty size. This already happens on Windows and MacOS, but not on Linux.
> [GTK] Ensure that layout is performed on all composites

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/JDialogTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/JInternalFrameTest.java
Due to the changes done by #379, the composites are now always location at (0,0). On Windows, they were offset by a small margin. But not on Linux. This has been harmonized.
> Fix test failures in JDialog and JInternalFrame.

- .github/workflows/maven.yaml
- .mvn/extensions.xml
- pom.xml
As Tycho requires Java 17, only use Java 17 for verification, as we anyhow plan to move WB to Java 17
> Update to Tycho 3.0.4

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/property/FontPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/support/FontSupportTest.java
On the Linux build nodes, neither the Arial, nor the Tahoma font are installed. Replace them with the Sans and Monospace font, which should be available on all platforms.
Where necessary, the check has been restricted to be executed on Windows only.
> Fix test failures in FontProperty and FontSupport.

- org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
When calling the beginShot() method, the redraw flag of the SWT widgets is set to false. In order to re-enable them after the shot has been taken, the endShot() method of the parent class has to be called as well. See fixZeroSizes_begin() and fixZeroSizes_end() for more details.
Amendment to #eba7cb5
> [GTK] Enable the redraw flag after screenshot has been taken

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/ExpandBarTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/TableGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/TableTest.java
Until this has been addressed via #389, disabling them should prevent them from obscuring other test regressions.
> Temporarily disable test cases related to empty bounds on Linux.

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/converter/ColorConverter.java
When converting system colors back to Java source code, the resulting String may be system-dependent. This happens if multiple colors have the same RGB values.
For example, the textHighlight color has the RGB values (0,120,215) on Windows but (0,0,0) on Linux. It may therefore simply be represented by the color black. This means that if a screen was created on Linux, but then opened on Windows, the screen ends up using the wrong color!
In order to avoid this ambiguity, identity is used, in addition to equality. If the given color is identical one of the color constants, then its String representation is returned by the converter. Otherwise, the first compatible String representation is returned instead.
Example:
java.awt.SystemColor.textHighlight -> java.awt.SystemColor.textHighlight …
> String representation of system colors may be ambiguous.

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/layout/table/TableWrapLayoutConverter.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/grid/GridLayoutConverter.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XML/model/generic/FlowContainerModelTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XML/model/generic/SimpleContainerModelTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/ObjectInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/association/CompoundAssociationTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/generic/FlowContainerModelTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/editor/AbstractTextPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/util/JavaInfoUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/refactoring/RefactoringUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/nebula/GanttChartTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/nebula/GridTest.java
As part of e.g. the GEF migration, we have to adapt a lot of package names. Cleanup the packages in preparation, to avoid any unrelated file modifications.
> Perform automatic code cleanup - Organize Imports

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/laf/LookAndFeelTest.java
With newer Java versions, it is no longer allowed to access the internal com.sun.* classes directly. Instead, their qualified name has to be encoded as a String and passed to the UIManager instead.
> Repair & execute disabled Look and Feel test cases.

- org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
- org.eclipse.wb.os/src/org/eclipse/wb/os/OSSupport.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingUtils.java
Our JUnit tests frequently get stuck on Linux while trying to draw Swing components. And I think what's happening is the following: The UI update is executed from within the main thread while at the same time, another UI update is executed from the AWT EventQueue. The way GTK handles this parallel is by occasionally locking up.
One of the comments in the SwingUtils class describes it as follows:
> Linux synchronizes GTK calls and if being invoked from different
threads it may lock up.
To solve this problem, check whether we are current in the EventQueue. If so, run the job as normal. Otherwise submit the job to the EventQueue and wait for its completion. This way, we ensure that all Swing operations are executed from within a single thread.
> [GTK3] Fix freeze if using GTKLookAndFeel in Swing + SWT

- org.eclipse.wb.core.lib/.classpath
The plug-in "org.eclipse.wb.core.lib" specifies the 'src' folder in its classpath, even though the bundle only contains jar. This never caused problems up until recently, until the MVEL2 jar has been deleted.
Given that this folder isn't needed, we simply have to remove this entry from the classpath.
> Resolve "missing required source folder" error

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/AbstractJavaProjectTest.java
Primarily on Windows, we get sporadic test failures of the form:
-> /TestProject/src/test/Test.java already exists in target
This error shows up at the start of a test, when creating a new test screen. The exact reason is not clear, but it's most likely a timing issue. It might for example be that the auto-build is still running, thus preventing the Eclipse to delete the file from the file system.
This issue should be avoided by using the harsher forceDeleteFile() method, instead of calling resource.delete(). This way we can be almost certain that the file is gone, by the time the next test is executed.
Another common issue is of the form:
-> java.lang.ClassNotFoundException: test.MyComposite
This error shows up when trying to parse a Java file which hasn't been created yet. Again, the …
> [JUnit] Attempt to stabilize the set-up/tear-down phase for each test.

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/TreeRobot.java
There are currently two test failures on the Jenkins build, both in the MenuComplexTest. The first failure happens during the clean-up phase in 'test_deleteItemWithSubmenu' because the menu item couldn't be deleted in time.
This test sporadically succeeds, which makes me believe that this is a timing issue and some SWT events that are fired haven't been processed by the time we attempt to remove it. To solve this issue, pump SWT events for a short amount of time after changing the selection.
The second failure is a result of the first failure. Because the first test fails during the tearDown() call, the created Java file isn't deleted. When trying to create a new one for the next test, we fail because a file with the same name already exists.
> [JUnit] Attempt to stabilize Jenkins build.

- setups/WindowBuilder.setup
The Oomph setup script is no longer compatible with the current state of the WindowBuilder master. This is because the script creates a modular target platform consisting of the Maven dependencies specified in wb-mvn, as well as some hardcoded p2 repositories. We therefore miss out on the remaining update sites, which are used by Tycho (e.g. Nebula).
Instead of manually having to keep both files in sync, I think it makes more sense to use the same target platform in the IDE that is used by Tycho.
This brings the following benefits:
- Changes to the target platform are automatically integrated into Oomph.
- Code that works in the IDE is likely to also work during the build.
> [Oomph] Update the setup task due to changes to the target platform

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/DesignerEditorTestCase.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/layouts/grid/GridLayoutGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuComplexTest.java
Create a new assertJavaInfo method, to check the whether a widget with the given name exists in the Java code. This is the underlying cause of the Jenkins failure, because no matching data binding can be found.
Furthermore, refresh the design page after it has been openend, to ensure that all data bindings are up-to-date.
Reactivate test_deleteItemWithSubmenu() as this is a general problem and not limited to just this test.
> Extend unstable tests with additional checks to isolate point-of-failure

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/PageLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/PdeUtilsTest.java
This view has been marked as deprecated in 3.5 with the recommendation to use the Common Navigator Framework instead.
As part of this removal, the ID_RES_NAV page layout is no longer going to be available, which is referenced in two of our test cases. Use the Project Explorer instead, given that it provides almost the same functionality, which is more than sufficient for the tests.
> Adapt test cases to the removal of the Resource Navigator.

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/TreeRobot.java
The problem is that the property table is redrawn while WB is still deleting the widget. So we're at a state where the widget has already been removed from the databinding but is still registered as selected.
When we then try to redraw the table, we attempt to fetch the no-longer-existing databinding for the widget, causing a model exception.
In short, instead of:
- Update Selection
- Update Databinding
- Redraw
We do:
- Update Selection
- Update Databinding
- Redraw <- Error
We already tried something similar with revision
ea5c81c078bb654efbe6214610e960b6dc1b0502. However just doing a single SWT event loop isn't enough.
Resolves #413
> [JUnit] Pump the SWT event queue for 100ms after selecting a tree object

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/AbstractJavaProjectTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/parser/ExecuteOnParseTest.java
Calling delete() just once may not be sufficient enough on Windows, to ensure that all files are actually removed from the file system. Use a similar approach to forceDeleteFile(), to make sure that it is cleaned up after/during a test.
> [JUnit] Gracefully handle deletion of Compilation Units on Windows.

- org.eclipse.wb.core.feature_feature/feature.xml
Because we started replacing embedded jars with their latest version from Maven Central or the SimRel repository, it is no longer possible to install WindowBuilder in a fresh Eclipse installation due to unresolved dependencies.
While it is possible to resolve this by manually adding those update sites, this is highly inconvenient and - for Maven dependencies - not always possible.
~~Because those are 3rd-party dependencies, I don't think they should be added to a project feature, in order to avoid redundancy with other features referencing the "same" bundles (i.e. same id, different version). Instead, add them directly to the repository as uncategorized artifacts.~~
Add those plugin to the relevant WB feature, to ensure that no left-over
plugin remains, in case the feature is removed from …
> Fix: "lastgoodbuild" update site misses dependent bundles

- target-platform/wb.target
The old version is no longer up-to-date, thus leading to unresolved dependencies.
We may require the latest milestone due to replacing embedded jars with their latest Maven/SimRel release. Once this is done we can switch to a fixed release, at least for the target platform.
> Replace the version of the SimRel feature with the 0.0.0 wildcard.

- org.eclipse.wb.swt/META-INF/MANIFEST.MF
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/utils/ResourceManagerClassLoaderInitializer.java
We use ByteBuddy/CGLib, to subclass the PluginResourceProvider, in order to inject a custom implementation of the getEntry() method.
> Replace the CGLib runtime code generation in WB SWT with ByteBuddy

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/AstNodeUtils.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/parser/SwingParserTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/AstNodeUtilsTest.java
The problem boils down to the fact that generic type informations are not stored inside the Java byte code. Meaning a generic method `foo(T t)` is stored as `foo(Object t)`.
In principle, WindowBuilder is able to correctly map those methods. But only for normal objects, not for arrays. This oversight has been corrected.
The reason it showed up for the JComboBox specifically is because of its generic constructor `<init>(T[] items)`, which is stored as `<init>(Object[] items)`.
Because our mapping mechanism wasn't working for arrays, we try to look up the constructor `<init>(String[] items)` when trying to instantiate the object. Because no match was found, an exception is thrown.
> Issue 352 - Parameterized JComboBox breaks Design tab

- org.eclipse.wb.core.java.feature_feature/.settings/org.eclipse.mylyn.tasks.ui.prefs
- org.eclipse.wb.core/src/org/eclipse/wb/core/branding/DefaultBrandingDescription.java
- org.eclipse.wb.doc.user/html/error_reporting.html
- org.eclipse.wb.doc.user/html/support/product_support.html
- org.eclipse.wb.doc.user/toc.xml
This fixes references to bugzilla and the old support forum by pointing to github issues and discussions.
> Fix bugzilla and forum links

- org.eclipse.wb.core.java/META-INF/MANIFEST.MF
- org.eclipse.wb.core/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp/META-INF/MANIFEST.MF
- org.eclipse.wb.tests/META-INF/MANIFEST.MF
The Eclipse 4.27 is using ASM 9.4. However, Windowbuilder requires at
least 9.5  Because this plugin is not contained by the target platform,
WindowBuilder can't be installed due to unresolved dependencies.
Adjust the lower bounds to 9.0 in the Manifest files.
> Fix: Can't install WB on Eclipse 4.27 and older

- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/parser/BindingContextClassLoaderInitializer.java
- org.eclipse.wb.rcp/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/FormPageInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/SectionPartInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/WizardPageInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ActionContainerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ContributionManagerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/GroupMarkerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ToolBarManagerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/ActionFactoryCreationSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/PageLayoutCreateFolderInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/PageLayoutCreationSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/util/ActivatorGetImagesByteCodeProcessor.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/DialogInfo.java
Most of the migration is pretty straight-forward. The only noticeable change is that we have to inject the Dialog-subclass directly into the composite classloader, in order to avoid a NoClassDefFoundException in the CreationSupport classes.
> Replace CGLib code generation in WB RCP with ByteBuddy

- org.eclipse.wb.swing.jsr296/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.jsr296/src/org/eclipse/wb/internal/swing/jsr296/model/FrameViewInfo.java
We only use CGLib/ByteBuddy to create a non-abstract subclass of the JDesktop Application class.
> Replace CGLib code generation in Swing JSR296 with ByteBuddy

- .github/workflows/maven.yaml
- org.eclipse.wb.tests/pom.xml
The Jenkins build currently sets two timeouts. A 90 min. timeout for the
entire build and a 60 min. timeout for the JUnit tests.
Whenever we want to adjust the timeout, we have to separate places to
edit (the pom.xml file on the test bundle and the Jenkinsfile). We
should drop the timeout of the tests and simply rely on the global
timeout.
Note that we GitHub workflow already has a timeout of 5h by default. It
is lowered to 90min to avoid excessive build times in case it ever gets
stuck and to keep in in sync with the Jenkins build.
>  Specify a global timeout of 90 min. for the GitHub build jobs

- target-platform/wb.target
This way WindowBuilder is built against the Eclipse 2023-06 and GEF 3.16. Furthermore, we list all required 3rd-party bundles from the SimRel repository, rather than simply importing everything.
> Update p2 repositories to their latest releases.

- org.eclipse.wb.rcp/wbp-meta/org/eclipse/ui/application/IWorkbenchWindowConfigurer.wbp-component.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/ActionBarAdvisorTest.java
This method has been deprecated decades ago and removed with the Eclipse 2022-12.
> Remove deleted IWorkbenchWindowConfigurer methods from wbp-component.xml

- org.eclipse.wb.rcp/wbp-meta/org/eclipse/jface/dialogs/PopupDialog.wbp-component.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/PopupDialogTest.java
This constructor has been removed with 2022-12. Use the non-deprecated constructor instead.
> Remove deleted PopupDialog constructor from wbp-component.xml.

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/creation/ThisCreationSupport.java
Using this strategy does not create a new class loader but injects all classes into the given ClassLoader by reflective access. This prevents the loading of classes with cyclic load-time dependencies but avoids the creation of an additional class loader.
Note that this strategy usually yields a better runtime performance.
> Enhanced classes should be directly injected in the parent class-loader

- .github/workflows/maven.yaml
- pom.xml
Resolving the target-platform definition currently takes forever... Let's try and see if the latest Tycho version can do better.
#481
> Update Tycho to the 4.0.0 nightly build.

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/PluginPalettePreferences.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/dialogs/PalettePreferencesDialog.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/editor/palette/PluginPalettePreferences.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/editor/palette/dialogs/PalettePreferencesDialog.java
- org.eclipse.wb.core/META-INF/MANIFEST.MF
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DefaultPalettePreferences.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IPalettePreferences.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
Unlike a Font, a FontDescriptor doesn't need to be explicitly disposed, minimizing the chance of a resource leak. The JFace ResourceManager may be used to manage multiple Font objects created from this descriptor.
Prerequisite for deprecating the SwtResourceManager.
See #260 #486
> IPalettePreferences should use FontDescriptor instead of Font

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/editor/palette/DesignerPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IEntry.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/test/PaletteTest.java
ImageDescriptors don't need to be explicitly disposed, reducing the change of a potential resource leak. Where necessary, the corresponding instance is created within the palette-composite via a local resource manager.
#260 #486
> Switch to the ImageDescriptor for IEntry instead of Image.

- .mvn/extensions.xml
- pom.xml
Tycho 4 has been released last week, meaning that the 4.0.0 nightly builds are no longer available. Instead of using the 4.0.0 release, we should continue to use the nightly builds, in order to respond to incompatibilities as fast as possible.
Even though Tycho 5 is still using Maven 3.9 right now, it will eventually require Maven 4 in the future.
> Update to Tycho 5 nightly build.

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/dialogfields/FontDialogField.java
When updating the font label, WindowBuilder creates a new font instance. This instance is never disposed properly, leading to the mentioned exception.
Given that the dialog field doesn't have a dispose() method, we can't use a resource manager to track this object. Instead, the lifecycle is bound to the lifecycle of the label it is assigned to.
> Fix "Widget is Disposed" exception in FontDialogField.

- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/IObservePresentation.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/presentation/JavaInfoDecorator.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/presentation/JavaInfoObservePresentation.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/presentation/ObservePresentation.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/presentation/SimpleObservePresentation.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/property/ObserveAction.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/property/SingleObserveBindingAction.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/providers/ObserveLabelProvider.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/util/ObjectInfoAction.java
- org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/EObjectObservePresentation.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/bindables/BeanBindablePresentation.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/contentproviders/ChooseClassAndTreePropertiesUiContentProvider.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/contentproviders/ViewerColumnsUiContentProvider.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/FieldBeanObservePresentation.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/contentproviders/ChooseClassAndPropertiesUiContentProvider.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/contentproviders/ColumnBindingUiContentProvider.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/contentproviders/el/ContentAssistProcessor.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/contentproviders/el/EvalutionLanguageConfiguration.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/wizards/autobindings/ObservePropertyAdapterLabelProvider.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/databinding/rcp/model/beans/BeanBindableTest.java
Image instances of those descriptors are handled via a resource manager. The lifecycle of the resource manager is bound to the lifecycle of its UI component.
For the ContentAssistProcessor, the resource manager has to be passed as an argument, due to the lack of a dispose() method. This manager is disposed together with the source viewer.
For the sake of simplicity, The ImageDescriptor.createForImage method is used to transform Images into ImageDescriptors. Example being e.g. the BeanBindablePresentation. Reason being that those images are used at multiple locations. Migrating them to ImageDescriptors would drastically increase the complexity of this change and should be handled by a separate commit.
> Switch from Image to ImageDescriptor for IObservePresentation

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/border/Border.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/border/CompoundBorder.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/EventManager.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/JustifyLabel.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/Label.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/VerticalLabel.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/handles/Handle.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/selection/ResizeHintFigure.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/selection/ResizeHintFigure.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/CompoundBorderTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/LineBorderTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/MarginBorderTest.java
Most of the GEF/Draw2D API expects an object of type IFigure as an argument. In order to simplify the migration to downstream GEF, our own figure implementation should implement this interface so that we can gradually build back our own classes.
Instead of implementing the entire IFigure interface, we instead extend the Figure base class, overwriting all non-trivial (and non-final) methods with the already existing implementation. Due to a bi-directional relation between Figure and Border, it is also necessary for our Border base-class to implement the corresponding Draw2D interface.
> [GEF] Figure should implement the IFigure interface.

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/MenuImageFigure.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/MenuItemEditPart.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/MenuPopupEditPart.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/menu/IMenuObjectInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/MenuManagerAdaptableFactory.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/MenuManagerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/MenuManagerPopupInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/menu/ComponentMenuItemInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/menu/JMenuBarInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/menu/JMenuInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/menu/JMenuItemInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/menu/JPopupMenuInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/menu/MenuInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/menu/MenuItemInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/widgets/menu/MenuItemTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/widgets/menu/MenuTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/MenuManagerTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/PageTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/ViewPartTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/menu/JMenuBarTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/menu/JMenuItemTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/menu/JMenuTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/menu/JPopupMenuTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/AbstractMenuObjectTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuItemTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuTest.java
- org.eclipse.wb.xwt/src/org/eclipse/wb/internal/xwt/model/widgets/menu/MenuInfo.java
- org.eclipse.wb.xwt/src/org/eclipse/wb/internal/xwt/model/widgets/menu/MenuItemInfo.java
The image stored in the IMenuObjectInfo instances are used for the presentation. We should switch to ImageDescriptors, to avoid "Widget is disposed" exceptions when closing the editor.
The getImage() method has been renamed to getImageDescriptor(). Where necessary, we use ImageDescriptor.createFromImage() to convert images to the correct type. Those images are slowly going to be transformed in ImageDescriptors in upcoming changes.
When drawing those components, a temporary Image instance is created.
> IMenuObjectInfo should use ImageDescriptor instead of Image.

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/surround/ISurroundTarget.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/surround/SurroundSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/util/surround/CTabFolderSurroundTarget.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/util/surround/SashFormSurroundTarget.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/util/surround/ScrolledCompositeSurroundTarget.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/util/surround/TabFolderSurroundTarget.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/util/surround/JPanelSurroundTarget.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/util/surround/JPanelWithBorderSurroundTarget.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/util/surround/JScrollPaneSurroundTarget.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/util/surround/JSplitPaneSurroundTarget.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/util/surround/JTabbedPaneSurroundTarget.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/util/surround/AbstractCompositeSurroundTarget.java
The icon in SurroundSupport is already converted into an ImageDescriptor internally. This change is a pre-requisite for changing the signature of the IObjectDescription.
Where necessary, images are converted to objects of type ImageDescriptor using ImageImageDescriptor.
> ISurroundTarget should use ImageDescriptor instead of Image.

- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/presentation/JavaInfoObservePresentation.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/InstanceFactoryEntryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/part/nonvisual/NonVisualBeanEditPart.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/editor/ObjectPropertyEditor.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/order/ReorderDialog.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/RenameConvertSupport.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gefTree/part/ObjectEditPart.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/model/ObjectInfo.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/util/ObjectsLabelProvider.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XML/model/XmlObjectRootProcessorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XML/model/property/EventsPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/NameSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/forms/ExpandableCompositeTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/jface/TableViewerTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/widgets/CBannerTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XWT/model/widgets/ViewFormTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/JavaInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ExposedFieldCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ExposedPropertyCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/EventsPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/util/ObjectsLabelProviderTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/ViewFormTest.java
- org.eclipse.wb.xwt/src/org/eclipse/wb/internal/xwt/model/property/editor/ObjectPropertyEditor.java
In order to switch to ImageDescriptors for IObjectPresentation, we first need to remove the singleton pattern from this label provider. We can create images from those descriptors using a resource manager. But if the instance of this provider is static, then those instances are not properly disposed.
The getImage() and getText() methods have been moved to ObjectInfo.
> Remove singleton pattern from ObjectsLabelProvider

- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
We have to use addMouseMotionListener() instead of addMouseMoveListener() to contribute the logic for reacting to mouse movement.
Former is contributed by the composite, latter by the figure. This error is an oversight after switching to the GEF mouse listener. Amends bac42ded3a2a3229e5d63159f5ee192b10100048
> Fix: Category not expanded when clicking on it.

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ActionInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/IActionIconProvider.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/ActionFactoryCreationSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/palette/ActionFactoryNewEntryInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/ActionTest.java
This stops the unnecessary wrapping from Images using the ImageImageDescriptor.
> IActionIconProvider should use ImageDescriptors instead of Images

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/CategoriesAndViewsDialog.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/PdeUtils.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/FolderViewInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/PageLayoutAddViewInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/shortcuts/FastViewInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/shortcuts/PerspectiveShortcutInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/shortcuts/ViewShortcutInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/palette/PerspectivePerspectiveDropEntryInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/palette/PerspectiveViewDropEntryInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/rcp/PdeUtilsTest.java
In order to keep the amount of changes per commit as small as possible, we convert Images to ImageDescriptors using the ImageImageDescriptor wrapper.
Instead of using this wrapper, we can use the descriptors directly.
> Replace icon wrapping for View/Shortcut info with pure image descriptors

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/FactoryEntryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/CreationDescription.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/factory/FactoryMethodDescription.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentPresentationHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/DescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/FactoryDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/presentation/DefaultJavaInfoPresentation.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/model/description/ComponentDescription.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/model/description/ComponentDescriptionHelper.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/model/description/ComponentPresentationHelper.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/model/description/CreationDescription.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/BundleResourceProvider.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/DefaultJavaInfoPresentationTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ExposedFieldCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ExposedPropertyCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/FactoryDescriptionHelperTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/description/CreationDescriptionTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/EventsPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/databinding/rcp/model/beans/BeanBindableTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/jface/ActionTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/ToolBarTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuItemTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/ButtonsTest.java
- org.eclipse.wb.xwt/src/org/eclipse/wb/internal/xwt/model/layout/AbsoluteLayoutInfo.java
Quite often, we still store icons as raw images and then wrap them as ImageDescriptors when needed. Which can be avoid by directly storing them as those descriptors.
> Cleanup internal Image wrapping in CreationDescription & friends

- org.eclipse.wb.core.java/src/org/eclipse/wb/core/editor/palette/model/entry/ComponentEntryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/FactoryEntryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/MorphingSupport.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/editor/palette/model/ComponentEntryInfo.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/model/utils/MorphingSupport.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/description/ComponentPresentation.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/external/ExternalFactoriesHelper.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/ImageUtils.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XML/palette/ComponentEntryInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/palette/ComponentEntryInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ExternalFactoriesHelperTest.java
The getImage() method in ExternalFactoriesHelper is no longer used. Instead, we use the logically identical getImageDescriptor().
> Cleanup internal Image wrapper in ComponentEntryInfo & friends

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/AbstractJavaProjectTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/DesignerEditorTestCase.java
The refresh call was added as part of the JUnit4 migration in an attempt
to stabilize some of the failing test cases. In return, this seems to
have destabilized previously stable tests, instead.
We also need to ensure that resources are ALWAYS deleted once a test
finishes, even if the test itself has failed. Otherwise those files may
leak into the next test.
> Cleanup tear-down methods to stabilize test cases

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/forms/table/TableWrapLayoutGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/layouts/grid/GridLayoutGefTest.java
The wait time for one of the TableWrapLayoutGefTest has been increased to 10ms, in order to ensure that the internal state of the properties table has been updated by the time the component is deleted.
Given that all of those operations normally happen synchronously, this shouldn't be a problem during normal usage, but something that only happens during tests, because they also run in the UI thread and thus SWT updates are only executed when explicitly requested.
To summarize the problem: The button was deleted from the data model, but not from the table. When the table was redrawn, it tried to load the button properties from the model and failed, because nothing was found.
> Adjust wait time for event loop to stabilize unit test

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/parser/AbstractParseFactory.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/CompositeClassLoader.java
This resolves the NoClassDefFoundError thrown by MVEL when trying to parse an expression via ScriptUtils. Internally, MVEL loads a class using our composite classloader which itself is based on the project classloader. This classloader is not the one that called MVEL and doesn't have its classes in its classpath. Simply adding this missing dependency solves this problem.
> Add MVEL bundle to the project classloader

- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/model/description/ComponentPresentationHelper.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/description/ComponentPresentation.java
The ComponentPresentation already uses ImageDescriptors internally, in order to store an image representation. The Image instance in this constructor is converted into an ImageDescriptor using the ImageImageDescriptor wrapper.
This constructor is only called inside the ComponentPresentationHelper, where we can directly switch to using ImageDescriptors as well, rendering this additional step obsolete.
> Remove obsolete Image constructor for ComponentPresentation

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/AbstractJavaProjectTest.java
If the test happens to fail due to an internal error, the cleanup task is never executed. This is resolved by puttin it in the finally block. Futhermore, we wait 10ms before and after disposing the project to ensure that the Eclipse had enough time to properly delete the project..
> Ensure that DisposeProjectAfter is always called after the test

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/ImageUtils.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/bindables/BeanBindablePresentation.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/bindables/BeanSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/bindables/LocalVariableBindableInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/DescriptionProcessor.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/bean/ActionInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingImageUtils.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/DescriptionProcessor.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ui/ImageUtilsTest.java
When converting an AWT image to SWT, the utility methods should return an ImageDescriptor instead of an Image. This way the calling method (i.e. our model classes) don't have to worry about disposing the image once no longer needed.
> Fix potential memory leak by using ImageDescriptors in ImageUtils

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
The item beneath the cursor is not drawn as etched-in. This is because this area is not included in the "damaged" area and thus not repainted. Adjust the calculation of the dirty region to match the code in the deleted RefreshManager to fix this issue.
Amends 7e95ab22602b957fb15106bbfb62c0b8df3d8b95
> Fix: Palette not properly updated when hovering over items

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/CharacterPropertyEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/binding/editors/SpinnerEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/binding/editors/controls/ComboSelectionEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/binding/editors/controls/RadioButtonsEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/binding/providers/IntegerPreferenceProvider.java
- org.eclipse.wb.rcp.databinding/resources/1.4/org/eclipse/wb/rcp/databinding/TreeBeanAdvisor.java
- org.eclipse.wb.rcp/resources/1.4/org/eclipse/wb/swt/SWTResourceManager.java
- org.eclipse.wb.rcp/resources/1.5/org/eclipse/wb/swt/DoubleFieldEditor.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/PreferencesRepairer.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/other/CastTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/primities/BooleanTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/primities/CharTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/primities/DoubleTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/primities/IntegerTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/primities/LongTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/StandardConvertersTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/accessor/FieldAccessorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/editor/DatePropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/editor/InstanceListPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/util/MethodOrderTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/GenericsUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/reflect/ReflectionUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/FormLayout/FormDimensionInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/property/FontPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/RequestsTest.java
Instead of e.g. new Integer(), we use the drop-in replacement Integer.valueOf().
> Remove usage of deprecated constructor for Java primitives.

- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/model/presentation/SimpleObservePresentation.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/ObserveElementsComposite.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/filter/AllPropertiesFilter.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/filter/PropertyFilter.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/filter/TypesPropertyFilter.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/bindables/PropertyBindableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/bindables/ViewerObservablePropertyBindableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/bindables/WidgetPropertyBindableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/contentproviders/TreeContentLabelProvidersUiContentProvider.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/filter/AdvancedPropertyFilter.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/filter/TypesPropertyFilter.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/providers/BindingLabelProvider.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/providers/PropertyAdapterLabelProvider.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/providers/TypeImageProvider.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/BeanPropertyObserveInfo.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/LocalVariableObserveInfo.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/VirtualObserveInfo.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/filters/HideAdvancedPropertyFilter.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/filters/ShowAdvancedPropertyFilter.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/filters/TypesPropertyFilter.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/providers/TypeImageProvider.java
The images stored by the TypeImageProvider have been changed from raw images to image-descriptors. The signatures of all classes referencing this provider have been adjusted to also use the descriptor, when possible.
When an instance of the image needs to be created, resource managers are used as much as possible. This should move the responsibility for disposing the images to the class that creates it and thus reduce the chance of unintentional memory leaks.
> Switch to ImageDescriptor in TypeImageProvider and adjust references

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/part/nonvisual/BeanFigure.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/BeanPropertyObserveInfo.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/BeanSupport.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/FieldBeanObservePresentation.java
We already convert images to descriptors on-the-fly. This is just a cleanup task to avoid this unnecessary wrapping.
> Store visuals of bean components as image descriptors instead of images

- org.eclipse.wb.dependencies.feature_feature/feature.xml
The Eclipse IDE doesn't depend on commons-collections. Because we have a direct dependency to it, this prevents WindowBuilder from being installed without additional update sites. Furthermore, this breaks the dropin mechanism.
The solution consists of simply adding it to the dependencies feature so that this dependency is also included in the update site.
> Fix: WindowBuilder can't be installed in Eclipse IDE

- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/beans/BeanSupport.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/beans/PropertyEditorWrapper.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/font/FontPreviewCanvas.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingImageUtils.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingScreenshotMaker.java
The createComponentShot now returns an image descriptor instead of an image. This resolves a potential memory leak in the BeanSupport class, when loading the beam images.
> Partial migrate SwingImageUtils to use ImageDescriptors.

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/MorphingSupport.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/factory/FactoryCreateAction.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/AstEditor.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/ExtensionElementProperty.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/ExtensionPropertyHelper.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/gbl/AbstractGridBagLayoutInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/BorderPropertyEditor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/LayoutAssistantSupport.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/NlsSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/AstEditorTest.java
The Guava functions have been more or less deprecated with the Java functions being the drop-in replacement
> Code Cleanup - Replace Guava Functions with Java Functions

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Polyline.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/Label.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/VerticalLabel.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/LabelTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/PolylineTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/RootFigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/TestCaseRootFigure.java
The reset method performs two tasks: revalidation and repaining.
In downstream GEF, this is split in two methods. Revalidation is done if
and only if the reset flag in our
implementation is set to true.
With this change, we ditch our implementation in favor of the intended
approach.
> [GEF] Synchronize reset method in Figure with downstream class

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
The font, visibility and opaque methods are already provided by the downstream Figure class. We should reuse those methods to reduce the amount of duplicate code and increase compatibility with the remaining GEF components.
> [GEF] Use downstream property methods in Figure class.

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/TestCaseRootFigure.java
In downstream GEF, painting is done by forwarding a request to the update manager. We implicitly do this already by calling parent.repaint() until we get to the root figure, meaning both implementation should be effectively identical.
> [GEF] Use downstream repaint methods in Figure class

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
The coordinates of the WindowBuilder figures are placed relative to the top-left corner of their parent. The useLocalCoordinates() method has to return true, otherwise the repaint operation will threat those as absolute coordinates and update the wrong area.
> [GEF] Fix: Repaint operation has to consider local coordinates

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/ReflectionUtils.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/wizards/project/NewProjectWizard.java
- org.eclipse.wb.rcp/templates/rcp/IPageBookViewPage.jvt
- org.eclipse.wb.rcp/templates/rcp/Page.jvt
- org.eclipse.wb.rcp/templates/rcp/PageIContentOutlinePage.jvt
- org.eclipse.wb.rcp/templates/rcp/PageIPropertySheetPage.jvt
- org.eclipse.wb.swing/templates/JDialog.jvt
- org.eclipse.wb.swing/templates/JDialog_buttons.jvt
- org.eclipse.wb.swing/templates/JFrame.jvt
- org.eclipse.wb.swing/templates/JFrame_advanced.jvt
- org.eclipse.wb.swing/templates/JInternalFrame.jvt
- org.eclipse.wb.swing/templates/JPanel.jvt
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/DesignerEditorTestCase.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/RcpTests.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/wizard/AbstractWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/wizard/Eclipse4WizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/wizard/JFaceWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/wizard/RcpWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/wizard/SwtWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/wizard/WizardTests.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/SwingNewWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/SwingTests.java
An exception is thrown when calling
getSite().getActionBars().getMenuManager(). When trying to resolve those
methods, we internally touch on methods hidden by encapsulation. This
then throws an unhandled InaccessibleObjectException exception.
Note: The problematic class is MethodHandles.Lookup in the Proxy class.
The Swing templates have been adapted to also generated the default
serialVersionUID in order to resolve the corresponding warning.
Test cases have been added to check, whether the design page can be
openened for all templates contributed via the New wizard.
This also resolves the missing serialVersionUID warning when creating
a new Swing widget.
> Fix: Unable to open design page for view page

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/AbstractTabItemInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/CTabFolderTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/TabFolderTest.java
The selection is not cleared when a tab item has been deleted. When updating the widget, we then run into an unhandled exception because the item we try to select no longer exists.
> Fix: Error when trying to delete selected tab item

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/utils/ProjectClassLoaderTest.java
Sometimes the test fails because the project location wasn't deleted by FileUtils.deleteQuietly. In order to resolve this problem (and to at least get a proper error message), we should use FileUtils.forceDelete() instead.
> Try to fix sporadic error thrown by ProjectClassLoaderTest

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/utils/ProjectClassLoaderTest.java
FileUtils.moveDirectory will try to remove the source folder (i.e. the IProject). This may conflict with the workspace resource. Given that we delete this project anyway, we should use copyDirectory() instead, which doesn't touch the source folder.
> Try to further stabilize the ProjectClassLoaderTest

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/top/SwingTopBoundsSupport.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingScreenshotMaker.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/top/JFrameTopBoundsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/top/JPanelTopBoundsTest.java
When the size of the frame exceeds the size of the screen, then the
frame will be maximized instead. As a result, the edges of the frame
outside the visible area won't be captured. This behavior can be
explicitly disabled by simply clearing the "resizable" flag.
> Fix: Swing components only partial captured when larger than screen

- org.eclipse.wb.core.feature_feature/feature.xml
- org.eclipse.wb.core.java.feature_feature/feature.xml
- org.eclipse.wb.core.java/META-INF/MANIFEST.MF
- org.eclipse.wb.core.ui.feature_feature/feature.xml
- org.eclipse.wb.core.xml.feature_feature/feature.xml
- org.eclipse.wb.dependencies.feature_feature/feature.xml
- org.eclipse.wb.doc.user.feature_feature/feature.xml
- org.eclipse.wb.layout.group.feature_feature/feature.xml
- org.eclipse.wb.os.feature_feature/feature.xml
- org.eclipse.wb.rcp.SWT_AWT_support_feature/feature.xml
- org.eclipse.wb.rcp.doc.user.feature_feature/feature.xml
- org.eclipse.wb.rcp.feature_feature/feature.xml
- org.eclipse.wb.swing.doc.user.feature_feature/feature.xml
- org.eclipse.wb.swing.feature_feature/feature.xml
- org.eclipse.wb.swing/META-INF/MANIFEST.MF
- org.eclipse.wb.swt.feature_feature/feature.xml
- org.eclipse.wb.xwt.feature_feature/feature.xml
- pom.xml
- target-platform/wb.target
- Update features to 1.14.0
- Increase Manifest versions due to changes since the 1.13.0
- Switch to Tycho baseline plugin -> More descriptive error messages and better customization. The Baseline check for features has to be disabled due to unreasonable increment requirements. :(
- Exclude Maven descriptor in bundled jars -> Due to the target-platform update, the pom dependencies might be updated, leading to changes in the binary file even though the bundle hasn't been modified.
> [SimRel] Update versions and target platform for next development cycle

- org.eclipse.wb.core.databinding.xml/META-INF/MANIFEST.MF
- org.eclipse.wb.core.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.core.ui/META-INF/MANIFEST.MF
- org.eclipse.wb.core.xml/META-INF/MANIFEST.MF
- org.eclipse.wb.core/META-INF/MANIFEST.MF
- org.eclipse.wb.layout.group/META-INF/MANIFEST.MF
- org.eclipse.wb.os.linux/META-INF/MANIFEST.MF
- org.eclipse.wb.os.linux/pom.xml
- org.eclipse.wb.rcp.SWT_AWT/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.databinding.emf/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.databinding.xwt/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.swing2swt/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.FormLayout/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.MigLayout/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.java6/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.jsr296/META-INF/MANIFEST.MF
- org.eclipse.wb.swt.widgets.baseline/META-INF/MANIFEST.MF
- org.eclipse.wb.swt/META-INF/MANIFEST.MF
- org.eclipse.wb.xwt/META-INF/MANIFEST.MF
Tycho recently updated to a new JDT version, which implements JEP-280.
This results in different byte-code for most of our classes, which is
detected by the baseline check. Increase the micro version of all
affected bundles to accommodate for this.
> Fix: Failure in tycho-baseline-plugin due to byte-code changes

- org.eclipse.wb.tests/META-INF/MANIFEST.MF
- org.eclipse.wb.tests/pom.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/UiContext.java
When an exception is thrown while running the executeAndCheck() method, it may happen that some of the created shells remain open. Whenever an exception is thrown (e.g. by a failed assertion), those shells are explicitly disposed to allow the run to continue.
> Fix: Deadlock when an exception is thrown inside an UIRunnable.

- org.eclipse.wb.tests/META-INF/MANIFEST.MF
- org.eclipse.wb.tests/pom.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/XML/palette/ui/PaletteUiTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/UiContext.java
Adjust the chooseComponentClass() to wait for the search text to be updated. It seems like the query from an earlier test is carried over. Furthermore, adjust the waitFor() method to always execute at least one cycle, in order to run idle UI events.
Revert "Fix: Deadlock when an exception is thrown inside an UIRunnable." This reverts commit 9d88d576a74534c300b41561f94b960647115f41.
> Second attempt to stabilize the PaletteUITests

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/order/TabOrderProperty.java
- org.eclipse.wb.swing/resources/1.8/org/eclipse/wb/swing/FocusTraversalOnArray.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/TabOrderProperty.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/TabOrderProperty.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/TabOrderPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/property/TabOrderPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/TabOrderPropertyTest.java
When a tab order is set for a Swing/SWT component, newly added elements should automatically be added to the end of the list.
> Fix: When tab order set, new tabbable controls not recognized

- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/ObserveElementsWizardPage.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/editor/contentproviders/LabelUiContentProvider.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/errors/MultipleConstructorsComposite.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/errors/NoEntryPointComposite.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/hierarchy/ComponentClassPropertyEditor.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/CustomTooltipProvider.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/JustifyPaletteTooltipProvider.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/selection/TopResizeFigure.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/errors/WarningComposite.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/contentproviders/el/KeywordsRule.java
We use the original font to create its bold variant. However, we never actually dispose this new instance, resulting in WidgetIsDisposed exceptions. The lifetime of those new fonts are now bound to its closest widget.
Amends e3f251258d6dae9939064edbd299bdc363691e9d
> Fix: Improper use of FontDescriptor to create bold fonts

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/EventManager.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/EditEventManager.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/TreeEventManager.java
In order to migrate to the GEF FigureCanvas, we need to first implement a compatible EventDispatcher. The event-listener interfaces are no longer implemented by the event dispatcher, but rather by the lightweight system. Given that we don't use it yet, this class is imitated by adding the listeners directly to the canvas.
> [GEF] Synchronize EventManager with GEF EventDispatcher

- target-platform/mvn/wb-mvn.target
MVEL is internally referencing java.lang.Compiler, which has been removed with Java 21:
https://bugs.openjdk.org/browse/JDK-8205129
Update MVEL from 2.4.15 to 2.5.0, where this issue has been resolved.
See #579
> Fix: NoClassDefFoundError in MVEL when using Java 21

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/ColorRegistryInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/FontRegistryInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/ResourceRegistryInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/ResourceRegistryRootProcessor.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ResourceRegistryTest.java
When we create instances of various ResourceRegistrys, for example ColorRegistry, they usually want to be disposed with Display, so they use Display#disposeExec(Runnable). But our Display instance lives all time while Eclipse lives. So, practically we have memory leak: we keep in memory instance of ResourceRegistry. its allocated resources, and what is much worse - instance of ClassLoader that loaded this ReourceRegistry.
The old implementation that used to explicitly dispose those objects was no longer functional and has been repaired.
> Fix: Potential memory leak due to undisposed resource registries

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/AbstractRelativeLocator.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/figure/TextFeedback.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/LayerTest.java
Our Designer figure currently has the local field "m_bounds" and "bounds", inherited from its parent class. The setBounds() method only updates the local field, which may lead to confusion when
a) debugging the application and
b) calling GEF methods, which may access the parent field directly
Given that both fields serve the same purpose, we might as well reuse the parent variable to avoid this problem. Note that this change also removes the setLocation(int, int) method, with its replacement being setLocation(Point). We only really use it in the TextFeedback class, so I don't think it's worth pushing this additional method to the downstream project.
> [GEF] Reuse bounds variable inherited from parent Figure class

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/LocalResourceManagerInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/ManagerContainerInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/LocalResourceManagerTest.java
By calling ManagerContainerInfo.getResourceManagerInfo(), WindowBuilder is able to create a local variable which may be used instead of the SWTResourceManager.
Prerequisite for #591
> Add methods to create LocalResourceManager instances on-demand

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/LocalResourceManagerInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/image/ImageDescriptorPropertyEditor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/image/ImagePropertyEditor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/preferences/IPreferenceConstants.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ImageDescriptorPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ImageDescriptorPropertyEditorTestNoManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ImageDescriptorPropertyEditorTestWithManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ImagePropertyEditorTestNoManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ImagePropertyEditorTestWithManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/LocalResourceManagerTest.java
This replaces the static call to our SWTResourceManager with calls to a
class-local instance of LocalResourceManager.
Example:
SWTResourceManager.getImage() ->
resourceManager.createImage(ImageDescriptor.createFrom()).
The usage of ResourceManager.getImageDescriptor() is removed completely,
with no replacement function. If users require custom image descriptor,
they need to create a subclass instead.
#591
> Replace usage of SWTResourceManager for images with LocalResourceManager

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/font/FontPropertyEditor.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/FontPropertyEditorTestNoManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/FontPropertyEditorTestRegistry.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/FontPropertyEditorTestWithManager.java
This replaces the static call to our SWTResourceManager with calls to a class-local instance of LocalResourceManager.
Example:
SWTResourceManager.getFont() ->
resourceManager.create(FontDescriptor.createFrom()).
#591
> Replace usage of SWTResourceManager for fonts with LocalResourceManager

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/LocalResourceManagerInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/jface/resource/ResourceManagerRootProcessor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/color/ColorPropertyEditor.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ColorPropertyEditorTestNoManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ColorPropertyEditorTestRegistry.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ColorPropertyEditorTestWithManager.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/LocalResourceManagerTest.java
This replaces the static call to our SWTResourceManager with calls to a
class-local instance of LocalResourceManager.
This also resolves several issues that I noticed while testing, where the resource manager was wrongfully created _after_ it was used inside a method call.
#591
> Replace usage of SWTResourceManager for colors with LocalResourceManager

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/property/CursorPropertyEditor.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/property/CursorPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/property/CursorPropertyEditorWithManagerTest.java
Instead of calling SWTResourceManager.getCursor(), we can simply use Display.getSystemCursor(). This has the added benefit that we don't need to explicitly dispose the cursors, once no longer needed.
#591
> Replace usage of SWTResourceManager for cursors

- org.eclipse.wb.doc.user/META-INF/MANIFEST.MF
- org.eclipse.wb.doc.user/html/features/custom_composites.html
When the "Use ResourceManager for color/font/image access" property is set, we currently copy a static SWTResourceManager class into the user workspace. This class is then used to manage those SWT objects.
Instead, we now simply create an instance object of LocalResourceManager into the currently active class, which those calls are delegated to.
This is part of the slow removal of the SWTResourceManager.
>  Update documentation to aligh with removal of SWTResourceManager. 

- .github/workflows/maven.yaml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/databinding/rcp/model/beans/BeanBindableTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/databinding/rcp/model/beans/BeanObservableTest.java
Note that the goal is not to require Java 21, just to make sure that WindowBuilder that it can be executed with the current LTS.
> Ensure forward compatibility by executing the tests with Java 17 & 21

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/PluginPalettePreferences.java
- org.eclipse.wb.core.xml/src/org/eclipse/wb/internal/core/xml/editor/palette/PluginPalettePreferences.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
The width and height of the palette entries (entry/components) is calculated using the font of the palette composite. Given that the user can set larger fonts for the entries, this may then end up in a situation where the text is larger than the figure, meaning the edges of the text are cut off.
This is fixed by using the correct font, in order to calculate the correct bounds of the figure using the Draw2D FigureUtilities class.
#605
> Consider the correct font when calculating the palette entry bounds

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/TestProject.java
Some of our tests occasionally fail due to a missing source folder in the test project. What's exactly causing this is not immediately obvious, but given that it only happens on Windows, the most likely candidate is its file management system.
If this case occurs, we now simply create a new source folder from scratch (while logging a warning), instead of simply throwing an exception.
> Try to minimize "Source folder not found" error during Windows tests

- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/wizards/autobindings/AutomaticDatabindingWizard.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/core/ProjectUtils.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/wizards/AbstractDesignWizard.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/wizards/RcpWizard.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/wizards/project/NewProjectWizard.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/wizards/SwingWizard.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/jdt/core/ProjectUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/SwingNewWizardTest.java
In case a project contains the module-info.java, the user has to manually add e.g. the "java.desktop" module, if they want to use Swing. If not, WindowBuilder will be unable to parse the source code and thus also unable to open the design page.
Given that in the project wizard, the checkmark to create this file is set by default, so it's very common to create and just forget about this file, when setting up a workspace.
Figuring out which modules to add is quite tedious and not immediately obvious for those not experienced with this feature, meaning we should attempt to automate this when possible.
Resolves #472, #473, #574, #592, #613
> Add required modules to module-info.java file when creating new template

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/layouts/grid/GridLayoutGefTest.java
The delete action is fired before the selection event has been fully processed, leading to occasional failures. By increasing the wait time, this should be avoided.
> Increase wait time for layout tests to 20ms to reduce instability.

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/EventManager.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/EditEventManager.java
In an earlier commit, the delayed execution of events was moved to the dispatch methods, instead of being implemented in the listeners directly. Because those methods are overwritten by the EditEventManager, this mechanism was no longer applied here.
Amends 9f074b858f5b5425864ecf669b6a100c417033c3
> Restore delayed event execution for EditEventManager

- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/SelectionTool.java
- target-platform/wb.target
Due to significant changes in GEF (primarily removal of raw types), we should check whether WindowBuilder still compiles with the latest milestone, in order to avoid any unpleasant surprises after the release.
> [SimRel] Build and test WindowBuilder against 2023-12 M3

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
Using the latest build may cause problems when new Tycho versions are built parallel to the WindowBuilder jobs. Avoid this by using a fixed version.
> Switch back to latest Tycho release (4.0.4) due to unstable builds

- org.eclipse.wb.releng.updatesite/category.xml
This way they can be consumed by the Oomph installer.
> Deploy the WB devtools to the p2 repository #644

- org.eclipse.wb.layout.group/META-INF/MANIFEST.MF
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutAligner.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutComponent.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutDesigner.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutDragger.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutFeeder.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutInterval.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutModel.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutOperations.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutUtils.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/support/SwingLayoutCodeGenerator.java
- org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/support/SwingLayoutUtils.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/assistant/GroupLayoutAlignmentPage.java
This fork is the cause of ~200 warnings regarding raw types, which make up about 1/4 of all warnings created by the builder.
Remark:
I thought about migrating to the upstream project: https://github.com/apache/netbeans/tree/master/java/form
However, the latest release already takes up 6MB, while our fork only requires 400kB...
```
<dependency>
<groupId>org.netbeans.modules</groupId>
<artifactId>org-netbeans-modules-form</artifactId>
<version>RELEASE200</version>
</dependency>
```
> Typify LayoutDesigner & friends in Netbeans Modules Form component

- org.eclipse.wb.rcp.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/DataBindingsCodeUtils.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/input/VirtualEditingSupportInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/widgets/observables/TextSwtObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/ui/contentproviders/ObservableDetailUiContentProvider.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/FieldEditorPreferencePageInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ActionContributionItemInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/PdeUtils.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/WorkbenchWindowAdvisorPropertiesProvider.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/AbstractPositionCompositeInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/AbstractTabFolderInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/CoolBarInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/ExpandBarInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/ToolBarInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/parser/ParseFactory.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/support/ToolkitSupportImpl.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/LayoutAssistantSupport.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/FormLayoutInfoImplClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/FormLayoutPreferences.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/actions/PredefinedAnchorsActions.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/menu/MenuInfo.java
In almost all cases, the call of Lists.newArrayList() can be simply replaced with new ArrayList<>().
We occasionally have to use Arrays.asList() or List.of(), depending on whether we expect null values and whether the list should be modifiable.
> Remove usage of Guava collections from SWT/RCP projects #270

- org.eclipse.wb.swing.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/decorate/BeanDecorationInfo.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/ui/property/BindingsProperty.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/AbsoluteLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/bean/AbstractActionInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/gbl/AbstractGridBagLayoutInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/parser/ParseFactory.java
Minor occurrences of collections and iterables which can be easilly expressed using native Java methods.
> Remove usage of Guava collections from Swing projects #270

- README.md
Contains instruction on how to build WindowBuilder locally, with and without tests.
> Add "How to build in command line" section to ReadMe

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/RootFigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/TestCaseRootFigure.java
Use getCursor() and setCursor() of the root figure instead. For updateCursor(), call EventDispatcher method directly.
> [Draw2D] Remove redundant cursor methods in Figure

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/nonvisual/ArrayObjectInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/parser/JavaInfoParser.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/AstEditor.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/DomGenerics.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/core/CodeUtils.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/AbstractJavaTest.java
This allows WindowBuilder to process new language features such as lambdas.
> Set JLS to latest (from Java 5 to Java 21)

- RELEASE_NOTES.md
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/event/ListenerInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/event/ListenerMethodProperty.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/LambdaTypeDeclaration.java
- org.eclipse.wb.jdt.fragment/META-INF/MANIFEST.MF
- org.eclipse.wb.jdt.fragment/src/org/eclipse/jdt/core/dom/LambdaMethodStub.java
- org.eclipse.wb.jdt.fragment/src/org/eclipse/jdt/core/dom/LambdaTypeStub.java
- org.eclipse.wb.tests/pom.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/EventsPropertyTest.java
WindowBuilder should now be able to recognize lambda expressions that are used to implement (event) listeners.
Example:
addHelpListener(e -> {
...
});
With limited functionality, it is also possible to use factory methods used by e.g. SWT.
Example:
addMouseListener(MouseListener.mouseUp(e -> {
...
}));
> Support of lambda expressions for listeners #176

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
Note that we now need to specifically call revalidate() for the PaletteComposite, as e.g. expanding or collapsing a category may also change the height of the whole palette.
Failing to do so would move entries outside of the scrollable area.
> [Draw2D] Harmonize setBounds method with downstream Figure

- org.eclipse.wb.core.java/src/org/eclipse/wb/core/gef/policy/TabOrderContainerEditPolicy.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/GraphicalEditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/TargetEditPartFindVisitor.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/figure/TextFeedback.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/SubmenuAwareEditPart.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/EditPartTest.java
We use the data field to keep track of the EditPart corresponding to a given Figure. The same functionality is provided by the VisualPartMap of the EditPartViewer interface.
> [Draw2D] Remove data field in Figure with GEF VisualPartMap

- org.eclipse.wb.dependencies.feature_feature/feature.xml
- target-platform/mvn/wb-mvn.target
Other SimRel projects currently use JAXB 2.3.9. In order to avoid having duplicate 3rd party libraries in the future, we should use the same artifact (albeit in a newer version).
> Switch to JAXB-OSGi from JAXB-Core + JAXB-Impl

- org.eclipse.wb.core.databinding.xsd/schema/wbp-component.xsd
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/CreationTagRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/CreationTypeParametersRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ModelClassRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MorphingNoInheritRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MorphingTargetRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ToolkitRule.java
Due to the complexity and required amount of change, each component is going to be migrated by a separate commit (as much as possible).
This is the first set of changes, consisting of the component toolkit, model, order creations and morphing targets.
#638
> Initial batch for migration from Digester3 to JAXB

- RELEASE_NOTES.md
- org.eclipse.wb.core.databinding.xsd/schema/wbp-component.xsd
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ExposingRulesRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MethodOrderDefaultRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MethodOrderMethodRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MethodOrderMethodsRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MethodsOperationRule.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/InvocationChainCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/description/ComponentDescriptionHelperTest.java
This change migrates handling of the component description, exposing rules, method order and in-/exclusions, as well as the untyped parameters to JAXB.
#638
> Second batch for migration from Digester3 to JAXB

- org.eclipse.wb.core.databinding.xsd/schema/wbp-component.xsd
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ConfigurableObjectListParameterRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ConfigurableObjectParameterRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MethodPropertyRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/PropertyCategoryRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/PropertyDefaultRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/PropertyGetterRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/PropertyTagRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesAdvancedRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesFlaggedRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesHiddenRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesNoDefaultValueRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesNormalRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesPreferredRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertiesRule.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/StandardBeanPropertyTagRule.java
The "parameter" and "parameter-list" elements of the property editor and configurable type have been moved to a common sub-type so that they can both be handled by the same method.
The "PropertyConfigurationElements" group has been converted to a complex type, extended by both the "PropertyConfiguration" and "MethodSingleProperty" type, in order to be handled by the same method.
The rules have been adapted to accept both Digester3 and JAXB instructions. This is because they are still used to process other properties, which still use Digester3, which would then inflate the amount of change that needs to be done per commit.
See #638
> Process the (standard bean) properties of a component via JAXB

- RELEASE_NOTES.md
- org.eclipse.wb.core.databinding.xsd/pom.xml
- org.eclipse.wb.core.databinding.xsd/schema/wbp-factory.xsd
- org.eclipse.wb.core.databinding.xsd/src/org/eclipse/wb/core/databinding/xsd/component/ContextFactory.java
- org.eclipse.wb.core.databinding.xsd/src/org/eclipse/wb/core/databinding/xsd/component/jaxb.index
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/FactoryDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/Messages.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/messages.properties
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/ActionFactoryCreationSupport.java
- org.eclipse.wb.rcp/wbp-meta/3.3/org/eclipse/ui/forms/widgets/FormToolkit.wbp-factory.xml
- org.eclipse.wb.rcp/wbp-meta/org/eclipse/jface/layout/GridDataFactory.wbp-factory.xml
- org.eclipse.wb.rcp/wbp-meta/org/eclipse/jface/layout/GridLayoutFactory.wbp-factory.xml
- org.eclipse.wb.rcp/wbp-meta/org/eclipse/jface/viewers/CheckboxTableViewer.wbp-factory.xml
- org.eclipse.wb.rcp/wbp-meta/org/eclipse/swt/awt/SWT_AWT.wbp-factory.xml
- org.eclipse.wb.rcp/wbp-meta/org/eclipse/ui/forms/widgets/FormToolkit.wbp-factory.xml
- org.eclipse.wb.swing/wbp-meta/javax/swing/Box.wbp-factory.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/FactoryDescriptionHelperTest.java
This removes the dependency on Digester3 when processing the wbp-* XML files. Note that there is no formal schema for the wbp-factory files, which is why one was created based on the wbp-component schema and the existing JUnit tests, but it might still be incomplete.
See #638
> Create wbp-factory schema and load model from XML via JAXB

- setups/WindowBuilder.setup
Dependencies like commons-collections4 are not part of the latest release repository yet. We need to also include the latest Orbit repository.
This also removes the GEF nightly repository. Instead, we fall back to the SimRel release.
> Consider SimRel Orbit repository when calculating the modular targlet

- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/Tool.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/ResizeTrackerTest.java
When dragging the cursor (e.g. to resize a figure), the corresponding tool would use the absolute coordinate of the cursor as start point, and the relative coordinate as end point when determining whether dragging should be enabled.
This fails once the user scrolled slightly to the right/down. To fix this, simply replace the call to getCurrentInput().getMouseLocation() with getLocation(), which returns the ABSOLUTE mouse location.
Resolves #697
> Use absolute coordinates for start and end location while dragging

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/core/ProjectUtils.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/parser/ParseFactory.java
- org.eclipse.wb.rcp/templates/e4/ViewPart.jvt
Eclipse IDE 4.30 added support for jakarta.annotation and jakarta.inject packages (https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2FwhatsNew%2Fplatform_whatsnew.html&cp%3D0_6_1&anchor=GeneralUpdates) which are now the default and added as dependencies to E4 RCP application plugins created with the PDE plugin wizard:
As a consequence, the root context parser needs to check for jakarta.annotation in addition to javax.annotation.
The WindowBuilder > SWTDesigner > Eclipse 4 > ViewPart wizard template should follow the IDE SDK 4.30 change to jakarta instead of javax and use the new namespace as well.
> Add jakarta namespace to root context parser for E4 parts

- setups/WindowBuilder.setup
Otherwise the setup fails when selecting "Eclipse SDK" rather than "IDE for Eclipse committers" in the Oomph dialog.
> Add missing m2e repository to P2 director

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/e4/E4PartTest.java
This test checks whether methods annotated with PostConstruct are detected as entry points for WindowBuilder. Note that this test now assumes that the jakarta namespace is used (even though javax should still work).
> Repair and execute E4 RCP test

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
The deselection of the palette entries is not registered on Windows. While the entry can be selected, it remains selected even if other entries are chosen.
This is because the setCapture() method in Figure was removed and therefore those method calls in the PaletteComposite now reference the Control method instead. The reason this doesn't affect Linux is because here this is a no-op method.
Amends 360a0a678fb52b7a8e33b5fbb97de7967e6cc069
> [Win32] Repair selection in WindowBuilder palette

- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/layout/flow/AbstractFlowLayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/generic/FlowContainerLayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/menu/MenuLayoutEditPolicy.java
- org.eclipse.wb.rcp.nebula/src/org/eclipse/wb/internal/rcp/nebula/collapsiblebuttons/CollapsibleButtonsLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/jface/DialogButtonBarLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/jface/action/ToolBarManagerLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/rcp/perspective/PageLayoutCreateFolderLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/rcp/perspective/shortcuts/FastViewContainerLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/rcp/perspective/shortcuts/PerspectiveShortcutContainerLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/rcp/perspective/shortcuts/ViewShortcutContainerLayoutEditPolicy.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/MigLayoutSplitEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/component/JTabbedPaneLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/component/JTabbedPaneTabLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/CardLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/GenericFlowLayoutEditPolicy.java
This removes the import of our EditPart subclass in favor of the GEF interface.
> Adapt FlowLayoutEditPolicy methods to use GEF EditPart directly

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/policy/nonvisual/NonVisualValidator.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gefTree/policy/ArrayObjectRequestValidator.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/policies/ILayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/AbstractLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/AbstractModelClassLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/BorderOfChildLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/CachingLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/CompatibleLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/ComponentClassLayoutRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/LayoutRequestValidators.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/generic/AbstractContainerRequestValidator.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/menu/MenuLayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/menu/SubmenuAwareLayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gefTree/policy/menu/MenuItemLayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gefTree/policy/menu/MenuLayoutEditPolicy.java
- org.eclipse.wb.rcp.nebula/src/org/eclipse/wb/internal/rcp/nebula/collapsiblebuttons/CollapsibleButtonsLayoutEditPolicy.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/jface/DialogButtonBarLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/menu/MenuBarDropLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/menu/MenuPopupDropLayoutEditPolicy.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/menu/MenuBarDropLayoutEditPolicy.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gefTree/policy/menu/MenuBarDropLayoutEditPolicy.java
This removes the import of our EditPart subclass in favor of the GEF interface.
> [GEF] Adapt ILayoutRequestValudator methods to use GEF EditPart directly

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/BooleanObjectPropertyEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/BooleanPropertyEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/PropertyEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/TextDisplayPropertyEditor.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/DrawUtils.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/beans/ComboPropertyEditor.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/beans/PropertyEditorWrapper.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/beans/TextPropertyEditor.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/color/ColorPropertyEditor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/color/ColorPropertyEditor.java
In preparation of converting the property table into a proper GEF viewer, the dependent classes need to be adjusted to use the Draw2D API.
This change only wraps the GC object in a Graphics object, which is is then passed as an argument to the property editors. Internally, this Graphics object then calls the corresponding GC methods.
In the future, this Graphics object is supplied by the viewer when painting the Draw2D figures and no longer needs to be constructed by us.
> [Draw2D] Paint property values using Graphics instead of GC object

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/variable/ExposedFieldVariableSupport.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/variable/FieldUniqueVariableSupport.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/variable/FieldVariableSupport.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/variable/LazyVariableSupportUtils.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/variable/VariableUtils.java
Use the JDT NamingConventions class for adding or removing the prefix and/or suffix of a given variable name. This avoids having to explicitly load the project-specific prefix/suffix properties.
Resolves #717
> Fix sporadic NullPointerException in VariableUtils

- org.eclipse.wb.core.databinding.xsd/META-INF/MANIFEST.MF
- org.eclipse.wb.core.databinding.xsd/pom.xml
- org.eclipse.wb.core.feature_feature/feature.xml
- org.eclipse.wb.core.java.feature_feature/feature.xml
- org.eclipse.wb.core.ui.feature_feature/feature.xml
- org.eclipse.wb.dependencies.feature_feature/feature.xml
- org.eclipse.wb.doc.user.feature_feature/feature.xml
- org.eclipse.wb.layout.group.feature_feature/feature.xml
- org.eclipse.wb.os.feature_feature/feature.xml
- org.eclipse.wb.rcp.SWT_AWT_support_feature/feature.xml
- org.eclipse.wb.rcp.doc.user.feature_feature/feature.xml
- org.eclipse.wb.rcp.feature_feature/feature.xml
- org.eclipse.wb.swing.doc.user.feature_feature/feature.xml
- org.eclipse.wb.swing.feature_feature/feature.xml
- org.eclipse.wb.swt.feature_feature/feature.xml
- target-platform/mvn/wb-mvn.target
- target-platform/wb.target
This change updates all features to 1.16.0, updates the target platform to use the 2024-06 repository and handles the changes detected in the XSD plugin.
To handle the timestamp in the generated JAXB files, a PR has already been created. In the meantime, we simply replace it using a small Ant script.
> [SimRel] Prepare workspace for 2024-06 release

- org.eclipse.wb.core/META-INF/MANIFEST.MF
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
In preparation for converting the property table in a GEF viewer, this change makes it so that the individual properties are drawn using the Draw2D Graphics object, rather than GC.
In the future, this painting is then done within a figure, where the Graphics object is automatically created by GEF and passed as a method argument.
> [Draw2D] Paint whole property table using Draw2D graphics object

- org.eclipse.wb.swt/META-INF/MANIFEST.MF
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/image/ImageDescriptorPropertyEditor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/image/ImageEvaluator.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/SwtInvocationEvaluatorInterceptor.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/utils/ResourceManagerClassLoaderInitializer.java
- org.eclipse.wb.tests/META-INF/MANIFEST.MF
- org.eclipse.wb.tests/pom.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ImageDescriptorPropertyEditorTestPlugin.java
This removes the internal usage of
ResourceManager.getPluginImageDescriptor() in favor of AbstractUIPlugin.imageDescriptorFromPlugin().
Note that the ResourceManager class is using a special PluginResourceProvider interface for loading bundle images at design time, because the widget class is not parsed within an OSGi environment and therefore Platform.getBundle() always returns null. To replicate this behavior, the method invocation is hijacked and replaced by a call to SwtInvocationEvaluatorInterceptor.getEntry() (the same method that is used by the ResourceManager).
See #486
> Use AbstractUIPlugin instead of ResourceManager to load ImageDescriptor

- org.eclipse.wb.core.java/src/org/eclipse/wb/core/editor/palette/model/entry/ComponentEntryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/BundleLibraryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/JarLibraryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/LibraryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/LayoutDescription.java
- org.eclipse.wb.core/schema/layoutManagers.exsd
- org.eclipse.wb.core/schema/toolkits.exsd
The layoutManagers and toolkits extension points have been adapted to not only support plain Java jars, but also proper OSGi bundles. To properly handle both types, the LibraryInfo class has been split into a JarLibraryInfo and a BundleLibraryInfo variant.
For bundles, we also compare the version specified in the bundle manifest with the bundle in the local classpath. If the version in the workspace is older than what's used by WindowBuilder, the jar is replaced.
> Add ability to contribute OSGi bundles as additional libraries

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/platform/PlatformInfo.java
The class has been marked for removal. Suggested replacement is org.osgi.framework.Version
> Remove usage of deprecated PluginVersionIdentifier

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/ModelMessages.java
The value is never used, so we can simply remove it.
> Fix: NLS missing message: ColorPreferenceChooser_Include

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/DesignerPlugin.java
This workaround has been introduced due to issues with CGLib. After moving to byte-buddy this section seems to be no longer necessary.
> Remove boot-classloader hack

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/FigureCanvas.java
Handles the deprecated usage of a buffered image inside the FigureCanvas class. In GEF, painting is done exclusively inside the UpdateManager. By doing so, we break convention which has unpleasant side effects where e.g. a paint event is processed, even though the "draw cached" flag is set.
> [Draw2D] Painting on FigureCanvas should be done in UpdateManager

- org.eclipse.wb.os.linux/META-INF/MANIFEST.MF
- org.eclipse.wb.os.linux/pom.xml
- org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/tests/DesignerTestCase.java
The method Shell.adjustTrim() has been replaced by a new method (with same name), which now expects two integers as as arguments. For the sake of backwards compatibility, we check the version of SWT and then call either one or the other method.
Furthermore, the memory leak in ClassUtils has been fixed, so we no longer need to handle this case in our test suite.
> Fix incompatibilities introduced with 2024-06 M2

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
Instead of casting the edit part to a PropertyEditPart, it is sufficient to use a plain GraphicalEditPart. Otherwise one runs into problems when clicking on e.g. the root edit part.
> Fix ClassCastException when double-clicking in property table.

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/presentation/ButtonPropertyEditorPresentation.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/presentation/ButtonPropertyEditorPresentationImpl.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/presentation/CompoundPropertyEditorPresentation.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/editor/presentation/PropertyEditorPresentation.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/alignment/AlignmentPropertyEditor.java
Instead of placing the buttons directly on the canvas, they are now
wrapped inside a Draw2D figure.
Via the paint() and erase() method, we control whether the buttons
should be shown or hidden. The bounds of the buttons are described by
the bounds of the figure.
To make this possible, the return value of the show() method has been
moved to a seprate getSize() method. This is necessary to calculate the
size of the figure without creating (and showing) the SWT widget.
> Integrate presentation buttons of property table into GEF layout.

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingScreenshotMaker.java
We explicitly cann frame.setResizable(false), in order to allow taking a screenshot for composites that are larger than the screen resolution. This has the unpleasant side effect that it's not possible to maximize the composite when opening the preview mode.
This property is now set before the screenshots are created and unset once everything is finished.
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/751
Amends 8c91b9b544942f659e93d824d9a22aaf3cabb5df
> Fix: Only disable resizability of frame when taking a screenshot.

- org.eclipse.wb.core.databinding.xsd/about.html
- org.eclipse.wb.core.databinding.xsd/build.properties
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/777
> Add missing about.html/plugin.properties to XSD bundle

- org.eclipse.wb.core.databinding.xsd/pom.xml
The XSD model generator doesn't overwrite an existing xjb file and is put next to it, instead. As a result, the ant-script no longer works as it can't find the correct file anymore.
> Clean the src-gen directory of the XSD bundle as part of the Maven build

- .github/workflows/license-review.yml
- .github/workflows/maven.yaml
- .github/workflows/unit-tests.yml
Tags are supposedly unsafe as they are not immutable. A malicious third party can potentially retag a release containing harmful changes, which would then be executed as part of the build.
Using the commit id makes this much more difficult, as this is not easily reproducible.
> Update GitHub workflow actions and use commit ids instead of tags

- org.eclipse.wb.core.ui/META-INF/MANIFEST.MF
- org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/LayoutsPreferencePage.java
The input of the combo viewer needs to be set before the databinding is created. Otherwise the initial selection can't be restored. When unchecking an element in the table, the old selection of the combo viewer needs read before the new input is set, otherwise this information is lost.
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/785
> Fix:Layout preference page doesn't keep default layout

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
- target-platform/wb.target
This effectively disables the scrollbar overlay so avoid weird situations where buttons can't be clicked because they are obscured by the srollbar itself.
Furthermore updates to the latest GEF build in order to fix other issues where the scrollbar bounds are not considered when updating the bounds of the root figure.
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/795
> Always show scrollbar in property table to avoid obscured buttons

- org.eclipse.wb.core/META-INF/MANIFEST.MF
The PropertyTable class calls the method FigureCanvas.setScrollbarsMode which has been introduced with the given version. Trying to use the editor with an older version otherwise leads to a NoSuchMethodError.
The bound is set implicitly via org.eclipse.ui, which re-exports the SWT bundle.
Amends e6c43ce3c25e2a893acf2e90e04dd0ba68402c7b
> Raise lower bound of SWT bundle to 3.126

- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/ObservableCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/BeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/DetailListBeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/DetailSetBeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/DetailValueBeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/ListBeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/SetBeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/ValueBeanObservableInfo.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/standard/BeanObservableDetailListCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/standard/BeanObservableDetailSetCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/standard/BeanObservableDetailValueCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/standard/BeanObservableListCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/standard/BeanObservableSetCodeSupport.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/standard/BeanObservableValueCodeSupport.java
Amends 43e676f2de7a2da38306bbe813252e77f65eee9f
See https://github.com/eclipse-windowbuilder/windowbuilder/issues/492
> Update JavaDoc to remove references to old Observable API

- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/model/beans/observables/MapsBeanObservableInfo.java
Here we're still using the deleted Pojo/BeanObservables, leading to crashes in the editor when being used.
https://github.com/eclipse-windowbuilder/windowbuilder/issues/783 https://github.com/eclipse-windowbuilder/windowbuilder/issues/492
> Remove usage old Observable API when using IObservableMap

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/ContainerInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/CompositeInfo.java
When a new instance of ImplicitLayoutCreationSupport is created, one must make sure that setJavaInfo is called. This is normally done when calling JavaInfoUtils.createJavaInfo().
Failing to do so results in a AssertionFailedException, when an object is removed from the container again. To reproduce, simply create a JFrame, add a JPanel and then immediately remove it again.
Amends 280f8aa3282dce10f92e7d2cbe7077071aa11836
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/813
> Fix partial initialization of ImplicitLayoutCreationSupport

- .github/workflows/license-review.yml
- .github/workflows/maven.yaml
The organisation has changed from eclipse to eclipse-dash. No clue why the URL forwarding doesn't work...
> Update organisation hosting the dash-license yaml file.

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/model/entry/BundleLibraryInfo.java
When a bundle is not in the workspace, the call to getResource() returns null, leading to an exception when trying to extract the bundle version.
We mustn't modify files outside the workspace, so we simply return early.
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/819
> Fix NPE when MigLayout bundle has been added as external jar

- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/EditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/IEditPartViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/AbstractEditPartViewer.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/EmptyEditPartViewer.java
With the exception of calling the fireActivated() and fireDeactivated() methods, the active() and deactivate() method of the GEF and WindowBuilder edit part are functionally identical. Given that we don't register any of those listeners to the edit parts, they become interchangeable.
The registerEditPart() and unregisterEditPart() methods of the viewer are replaced with the register() and unregister() methods within the edit part itself. In addition to registering the model, this method now also registers visuals and the accessibility edit part. Neither of which we currently use.
> [GEF] Remove duplicate activate/deactivate methods in edit part

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerEntry.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IEntry.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/test/PaletteTest.java
Because the IEntry interface is API, we can't simply rename the methods
to match the ones that are used by GEF. Instead, a new DesignerEntry
class is created, which serves as an adapter between the IEntry
interface and the PaletteEntry class.
The IEntry interface has been marked as deprecated and "for removal",
meaning that they can be removed after a two-year grace period, without
breaking API.
> [GEF] Make IEntry compatible with PaletteEntry

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerContainer.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/ICategory.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/test/PaletteTest.java
Because the IContainer interface is API, we can't simply rename the methods to match the ones that are used by GEF. Instead, a new DesignerContainer class is created, which serves as an adapter between the IContainer interface and the PaletteDrawer class.
The IContainer interface has been marked as deprecated and "for removal", meaning that they can be removed after a two-year grace period, without breaking API.
> [GEF] Make IContainer compatible with PaletteDrawer

- org.eclipse.wb.core.java/src/org/eclipse/wb/core/gef/part/AbstractComponentEditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/EditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/DragEditPartTracker.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/IObjectInfoEditPart.java
This method is not part of standard GEF and should therefore not be in the base class. Furthermore, this method always returns a plain CompoundCommand, except for the AbstractComponentEditParts, where it instead returns a CompoundEditCommand.
To keep things compatible, a new IObjectInfoEditPart interface has been created, that is implemented by the AbstractComponentEditPart. By default, the DragEditPartTracker uses a normal CompoundCommand. But if the target edit part happens to implement this new interface, then the CompoundEditCommand is used.
This change will greatly reduce the amount of places where we have to use the WindowBuilder-specific edit parts.
> [GEF] Move createCompoundCommand() method out of EditPart class

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/CoreEditPartConfigurator.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/EditPartFactory2.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/GenericContainersConfigurator.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gefTree/EditPartFactory2.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gefTree/GenericContainersConfigurator.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/IEditPartFactory.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/AbstractEditPartViewer.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/IEditPartConfigurator.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/MatchingEditPartFactory.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/EditPartFactory.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/header/HeadersEditPartFactory.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gefTree/EditPartFactory.java
- org.eclipse.wb.rcp.nebula/src/org/eclipse/wb/internal/rcp/nebula/gef/EditPartFactory.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/EditPartFactory.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/RcpPolicyConfigurator.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gefTree/EditPartFactory.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gefTree/policy/RcpPolicyConfigurator.java
- org.eclipse.wb.swing.jsr296/src/org/eclipse/wb/internal/swing/jsr296/gef/EditPartFactory.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/EditPartFactory.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/action/ActionDropPolicyConfigurator.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/menu/MenuDropPolicyConfigurator.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gefTree/EditPartFactory.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/EditPartFactory.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gefTree/EditPartFactory.java
We no longer define two createEditPart methods, one for the GEF EditPart and one for the WB EditPart, but instead only the former inherited from the parent interface.
This makes this interface eligible for removal at a later point.
> [GEF] Cleanup method signatures in IEditPartFactory to use GEF EditPart

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/top/SwingTopBoundsSupport.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingImageUtils.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingUtils.java
Our RunnableObjectEx and the Java Callable are functionally identical: The interface defines a single method, which returns a generic object and may throw an exception. So there is no need to use our own interface.
Where applicable, anonymous instances of this interface have been replaced with lambda expressions.
> Change signatures in SwingUtils to expect a Callable object

- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/IEditPartViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/DragEditPartTracker.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/TargetingTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/Tool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/ResizeTracker.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/TreeViewer.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/EmptyEditPartViewer.java
This makes it so that those sets work directly on the GEF edit parts instead of the WindowBuilder edit parts, thus matching the signatures of the Tool base class.
See https://github.com/eclipse-windowbuilder/windowbuilder/pull/829
> [GEF] Harmonize inclusion/exclusion set in tools

- org.eclipse.wb.core.java/src/org/eclipse/wb/core/editor/palette/model/entry/ComponentEntryInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/core/model/JavaInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/eval/evaluators/InvocationEvaluator.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/FactoryDescriptionHelper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/accessor/FieldAccessor.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/accessor/SetterAccessor.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/converter/StringConverter.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/editor/AbstractListPropertyEditor.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/core/ProjectUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/util/PropertyUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/execution/ExecutionUtils.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/PdeUtils.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/LayoutJavaInfoParticipator.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/gbl/GridBagConstraintsInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/spring/SpringAttachmentInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormUtils.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/LayoutJavaInfoParticipator.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/execution/ExecutionUtilsTest.java
Our RunnableObjectEx and the Java Callable are functionally identical: The interface defines a single method, which returns a generic object and may throw an exception. So there is no need to use our own interface.
Where applicable, anonymous instances of this interface have been replaced with lambda expressions.
> Change signature of runObjectIgnore to expect a Callable object

- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/Activator.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/core/model/JavaInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/clipboard/JavaInfoMementoTransfer.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/generic/FlowContainerFactory.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/editor/ConstantSelectionPropertyEditor.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/variable/NamesManager.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/AstNodeUtils.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/ui/JdtUiUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/BundleResourceProvider.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/AbsoluteComplexSelectionEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/SingletonExtensionFactory.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/execution/ExecutionUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/xml/AbstractDocumentEditContext.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/GroupLayoutParserVisitor2.java
- org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/ManagedFormInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/layout/table/TableWrapLayoutInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/PreferencePageInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/MenuManagerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ToolBarContributionItemInfo.java
- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/FormDimensionUtils.java
- org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/Activator.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/absolute/ConstraintsAbsoluteLayoutInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/gbl/GridBagLayoutInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/CompositeInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/support/AbstractSupport.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/support/ContainerSupport.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/execution/ExecutionUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/TreeRobot.java
Our RunnableObjectEx and the Java Callable are functionally identical: The interface defines a single method, which returns a generic object and may throw an exception. So there is no need to use our own interface.
Where applicable, anonymous instances of this interface have been replaced with lambda expressions.
> Change signature of runObject/runObjectUI to expect a Callable object

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/PdeProjectConversionUtils.java
Some of our tests convert a Java project into a plug-in project using the internal PDE class. This class has been removed in favor of the (also) internal PluginProject class.
> Fix compilation error due to deleted PDE class

- setups/WindowBuilder.setup
The dictionary for spell-checking is located in org.eclipse.wb.core. When the workspace is created by the Oomph installer, this file should be used to avoid warnings caused by unknown technical terms.
> Set the "Dictionary" preference as part of the Oomph setup

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/AbsoluteComplexSelectionEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/actions/AnchorsActionsSupport.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupSelectionEditPolicy2.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/AnchorsSupport.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/LayoutAssistantPage.java
With this, bundles no longer need to contribute the actions icon on their own and instead, the images contributed via the CoreImages are used.
> Use new high-DPI icons for anchor actions

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
An exception is thrown when trying to add a figure that already has a parent. In downstream GEF, this would normally simply reparent the child. With this change, we mimic the GEF behavior in order to allow for an easier migration in the future.
> [Draw2D] Support reparenting when adding new child to figure

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/JustifyPaletteTooltipProvider.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/figure/OutlineImageFigure.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/AbsoluteBasedLayoutEditPolicy.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupLayoutEditPolicy2.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicy2.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicyClassic.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureEventTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/LayerTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/RootFigureTest.java
When adding a figure, one can currently only specify its bounds as additional argument. Normally, this constraints may be arbitrary (e.g. GridData for the GridLayout or a Rectangle for the XYLayout).
This argument is therefore simply passed to the layout manager (if present) instead being treated as the figure bounds. As a result, all references (which luckily only includes instances there the OutlineImageFigure is used) have been updated so that the bounds are explicitly set by calling setBounds(), rather than implicitly via add().
One could've achieved a similar effect by using the XYLayout. However, this would then only update the bounds during the re-layout and has been avoided to remain as close to the previous behavior as possible.
> [Draw2D] Add support for layout managers to figures

- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
In order to respond to size-changes in the palette when e.g. a container has been opened, we perform a re-layout whenever setBounds() is called. When a layout manager is set within a figure, this setBounds() method may also be called while performing the re-layout, leading to an infinite, recursive loop.
To avoid this, a revalidation is only done, after a category has been expanded/collapsed, or if the palette preferences have been updated.
> [Draw2D] Fix potential deadlock in palette when using layout manager

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/part/DesignRootEditPart.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/FigureUtils.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/policies/DirectTextEditPolicy.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/policies/GraphicalEditPolicy.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/TargetEditPartFindVisitor.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/part/jface/ControlDecorationEditPart.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/rcp/perspective/AbstractPartSelectionEditPolicy.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigurePaintingTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/RootFigureTest.java
This makes it so that the add(), remove() and setParent() methods of our Figure class match the ones defined by the GEF figure. Doing so avoids any ambiguity regarding which list a child is added to.
> [Draw2D] Harmonize Parent/Children accessors in Figure with base class

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/part/DesignRootEditPart.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Layer.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/AbsoluteBasedLayoutEditPolicy.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupLayoutEditPolicy2.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicy2.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuFeedbackTester.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/GraphicalRobot.java
The type cast is only necessary when using the visitor. For all other instances, we can work directly on the IFigure interface. Meaning there is no need to overwrite this method anymore.
> [Draw2D] Remove explicit type cast in Figure.getChildren()

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerRoot.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/test/PaletteTest.java
Because the IPalette interface is API, we can't simply rename the methods to match the ones that are used by GEF. Instead, a new DesignerRoot class is created, which serves as an adapter between the IPalette interface and the PaletteRoot class.
The IPalette interface has been marked as deprecated and "for removal", meaning that they can be removed after a two-year grace period, without breaking API.
> [GEF] Make IPalette compatible with PaletteRoot

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/ComponentInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingUtils.java
A race condition may occur when calculating the relative location of a Swing component relative to its parent component. The way we calculate this value is by subtracting the screen location of the child from the screen location of the parent. Because those locations are fetched independent from one another, it may happen that the window is moved between those requests, introducing a ficticious offset.
To avoid this issue, both locations have to be fetched at the same time, for which a new method getRelativeLocation() has been added to the SwingUtils class.
> Fix: Wrong coordinates when calculating location of Swing components

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingUtils.java
The getRelativeLocation() asynchronously calculates the screen location of the parent and child component. To calls should instead be done synchronously, to avoid any race conditions caused by window changes between those calls.
Amends bee6c0d65382e283c3e337f6f373a715fa6c0914
> Avoid asynchronous task when calculating relative locations

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
When trying to remove a "null" figure, an IllegalArgumentException is thrown instead of a NullPointerException.
> Adapt FigureTest to handle new GEF behavior

- .github/workflows/unit-tests.yml
The workflow action no longer creates a comment containing the test results on a given pull requests. Based on the log, it seems to be unable to find the PR...
This is an attempt to solve this issue by giving write-access to pull requests, as listed by the minimal workflow job permissions.
See:
https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md#permissions
> Explicitly set required permissions for "Publish Test Results" action

- Jenkinsfile
This is required to avoid excessive disk usage.
> Restrict the number of builds to keep with artifacts

- pom.xml
This plugin is referenced via the Tycho pomless build. If the version isn't set, a warning is created at the start of the build.
> Set version for builder-helper-maven-plugin

- org.eclipse.wb.core.databinding.xsd/pom.xml
This version isn't set anywhere, resulting in an illegal POM that produces a warning at the start of the build.
> Set version attribute for maven-clean-plugin

- org.eclipse.wb.doc.user/META-INF/MANIFEST.MF
- org.eclipse.wb.doc.user/html-src/faq.asciidoc
- org.eclipse.wb.doc.user/html-src/layoutmanagers/index.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/palette.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_image.asciidoc
- org.eclipse.wb.doc.user/pom.xml
- pom.xml
layoutmanagers/index.asciidoc
- table missing leading separator
faq.asciidoc
- unterminated table block
userinterface/palette.asciidoc
- section title out of sequence: expected levels 0 or 1, got level 2
userinterface/property_editor_image.asciidoc
- unknown style for listing block: java
> Fix several AsciiDoc errors/warnings/debug problems

- org.eclipse.wb.core/META-INF/MANIFEST.MF
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/HeaderGraphicalViewer.java
GEF automatically adds the H_SCROLL/V_SCROLL styles when creating a new FigureCanvas instance, leading to scroll-bars being shown in the headers and thus obscuring the entries.
Set the visibility of the scroll-bars to never be shown, to get around this problem. Note that those headers scroll together with the main viewer and the scroll-bars are therefore not needed.
Relates to:
https://github.com/eclipse-windowbuilder/windowbuilder/discussions/894
> Make scroll-bar invisible for horizontal/vertical header

- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/EditDomain.java
Both methods now overwrite the method inherited from the GEF EditDomain, thus preventing accidentally calling the wrong method due to overloaded methods.
> Harmonize setDefaultTool() and setActiveTool() methods in EditDomain

- pom.xml
The repository containing this plugin is only available when the "sign" profile is used, leading to several warnings during the normal build. This entry is only used to specify the version, which has simply been moved to the declaration.
> Remove eclipse-jarsigner-plugin from pluginManagement block

- setups/WindowBuilder.setup
The windowbuilder-website repository now contains the static HTML generated by Hugo. Users should never need to edit them directly, but rather modify the source files located in windowbuilder-website-source.
> Update URL to WindowBuilder Website repo in Oomph script

- org.eclipse.wb.rcp.SWT_AWT/META-INF/MANIFEST.MF
The 3.20 version won't be available before the 2024-12 release. Given that we only need this dependency to resolve "org.eclipse.gef.Tool", we can safely pick any recent version. The 3.18 version has only be chosen because that's what's used everywhere else as lower bound.
Amends 5562ca79b8be01aea8092a69ceda9eb1230392e7
> Adjust lower bound of GEF dependency in SWT_AWT.

- org.eclipse.wb.core.java/META-INF/MANIFEST.MF
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalettePopupActions.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/PluginPalettePreferences.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/dialogs/PalettePreferencesDialog.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerPaletteViewerPreferences.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IPalettePreferences.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
This marks the IPalettePreferences and DefaultPalettePreferences as "forRemoval", and replaces them with PaletteViewerPreferences class. The constants for the different palette layouts are also replaced with what is declared by GEF.
Preferences are now tracked by the DesignerPaletteViewerPreferences class, which is also used to define our own preferences.
> Synchronize IPalettePreferences with PaletteViewerPreferences

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerContainer.java
By overwriting the deprecated getEntries() method (which internally delegates to getChildren()), we may return a different list of palette entries, depending on which method is called.
> Harmonize call to palette entries in DesignerContainer

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/AbstractSWTBotTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/AbstractWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/UIUtil.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/WindowBuilderProjectExplorerBot.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/WindowBuilderWorkbenchBot.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/rcp/wizard/JFaceWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/rcp/wizard/RcpWizardTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/swing/wizard/SwingNewWizardTest.java
This removes the dependency from the AbstractSWTBotTest class to the AbstractJavaProjectTest class and therefore makes the SWTBot tests independent from the "old" tests.
This dependency was used to perform I/O operations, which is problematic due to its dependency on the UI thread. Instead, helper methods have been added to our custom SWTBot instance, which take over this task.
> Cleanup and decouple SWTBot from other JUnit tests

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/binding/DesignerMethodBinding.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/Messages.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/messages.properties
The JDT compiler is unable to calculate the argument names of a method binding when a JDK 8 is used and simply returns an empty array. This then leads to an out-of-bounds exception, as the number of parameter types no longer matches the number of parameter names.
Note that this issue only happens with a proper JDK 8, but not an e.g. JDK 17 with compiler compliance set to Java 8.
The parameter names themselves only seem to be relevant for cosmetic reason, so they are now simply ignored (together with a warning), rather than causing the editor to crash.
From a technical perspective, the problem can be isolated to one of the internal classes of the JDT compiler:
org.eclipse.jdt.internal.compiler.classfmt.MethodInfo
-> getArgumentNames()
-> readCodeAttribute()
-> decodeCodeAttribute()
The …
> [1.8] Improve support for outdated JDK versions

- org.eclipse.wb.swing/META-INF/MANIFEST.MF
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/laf/LafPreferencePage.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingUtils.java
- org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite.java
- org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite2.java
The applet that is created as part of the preview needs to be created and disposed from within the AWT even thread, to avoid deadlocks when called from within the SWT UI thread.
See https://github.com/eclipse-windowbuilder/windowbuilder/discussions/937
> Manage lifecycle of preview in LAF preference page via AWT even thread

- .github/workflows/license-review.yml
- .github/workflows/maven.yaml
- Jenkinsfile
The Eclipse Platform SDK now requires at least Java 21 due to Lucene 10.x and we therefore can no longer build against older versions.
> Build and test WindowBuilder against Java 21 only

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/DetailsPageTopBoundsSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/MasterDetailsBlockTopBoundsSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/SectionPartTopBoundsSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/CoolBarManagerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/jface/action/ToolBarManagerInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/ViewPartLikeInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/WorkbenchPartTopBoundsSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/PageLayoutTopBoundsSupport.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/rcp/perspective/shortcuts/AbstractShortcutInfo.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/widgets/CTabItemInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/property/ConvertersTest.java
In cases where an SWT widget has already been loaded, we can avoid the reflective calls by constructing the Draw2D rectangle directly.
> Refactor unnecessary usage of RectangleSupport class

- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/support/ToolkitSupportImpl.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/menu/MenuInfo.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/support/IToolkitSupport.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/support/ToolkitSupport.java
Also removes the unused "Image" utility methods.
Contributes to
https://github.com/eclipse-windowbuilder/windowbuilder/issues/942
> [eRCP] Typify IToolkitSupport interface

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/ICategory.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IEntry.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IPalette.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/IPalettePreferences.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
Primariy handles the warnings introduced by deprecating the IEntry, IContainer and IPalette interfaces.
> Cleanup deprecation warnings in palette-related classes

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPaletteEditDomain.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerEntry.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/EnvironmentUtils.java
- org.eclipse.wb.doc.user/html-src/whatsnew/index.asciidoc
- org.eclipse.wb.doc.user/html-src/whatsnew/v118.asciidoc
This re-implements the palette using the native GEF classes.
Open topics:
- Look & Feel
- Dragging of categories
- Tooltips
> PoC - Migration to PaletteViewer

- org.eclipse.wb.os.win32/src/org/eclipse/wb/internal/os/win32/OSSupportWin32.java
The win32_new() method now requires the native zoom level as additional argument.
> [win32] Adapt creation of Image instance to new method signature

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
Follow-up to dfb85a9419c0e55991e8cfdbb9efaacd8e01bed0 due to which the m_paletteComposite field is only initialized when the GEF palette is enabled.
> Fix NPE when opening palette settings dialog

- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/CCombo3.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/CComboBox.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/CTableCombo.java
The TypedListener has been deprecated with 2025-03 and is the reason WindowBuilder is binarily incompatible with older SWT releases. Instead of wrapping the listeners with a TypedListener, one can directly pass them to the non-deprecated addTypedListener() method.
> Remove usage of deprecated TypedListener

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
Using a FlowLayout over the GridLayout is the logical choice, given that each property is supposed to fill a single row. Doing so also avoids the ugly workaround of explicitly setting the grid-data constraints for each property figure.
Note that using this layout requires to explicitly enable width and height tracking in the view port, as otherwise the scrollbars are not properly shown when the table exceeds the client area of the underlying figure canvas.
> Use FlowLayout instead of GridLayout for property root edit-part

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/structure/property/ComponentsPropertiesPage.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/ModelMessages.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/ModelMessages.properties
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
When a property is selected, this now also selects the corresponding edit part. Doing so allows us to check whether an edit part is selected by simply checking the getSelected() flag, rather than having to compare against the local variable of the property table.
To do so, the setActivePropertyInfo(PropertyInfo) now delegates its call to select(EditPart), which not only updates the local variable but also notifies the underlying viewer about this change. This can then be utilized in the isActiveProperty() method of the PropertyFigure.
> Harmonize property selection with edit-part selection

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
If the table is refreshed due to editing a property, it may happen that the table is scrolled to the very top and thus hiding the selection. This is because the active property is set before the new input. Thus the selection is done on an outdated edit-part.
Instead the input should be set before the selection. Furthermore, the input needs to be validated, to ensure that the bounds of the figures are correct.
> Avoid jumping if property table is refreshed by a change

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/WindowBuilderProjectExplorerBot.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/WindowBuilderWorkbenchBot.java
The title was changed from "Select a wizard" back to "New" via https://github.com/eclipse-platform/eclipse.platform.ui/pull/2827
> Adapt tests to updated "New Wizard" title

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPaletteEditPartFactory.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/ISubPaletteInfo.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/DesignerSubPalette.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/palette/SwingPaletteEntryInfo.java
Previously, clicking on the "Choose Swing Component" entry would spawn a
separate palette in a new shell. This approach doesn't really work when
using a GEF viewer.
Instead, this entry is converted to a drawer. The Swing component can be
revealed and/or concealed by clicking on it.
> Realize SwingPaletteEntryInfo as a PaletteDrawer

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/PropertyEditPart.java
With to the 4f3e7ed284fa91f6db26f3bdd26eb72f5ff18b89, the property figures have been split up in a title and value figure. The width of the title figure is determined by the position of the splitter and therefore needs to be adjusted, whenever the splitter is moved.
> Update size of TitleFigure whenever the splitter is moved

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/DesignerPlugin.java
The current version of BurningWave is incompatible with Java 24 and causes a crash whenever the editor is opened.
Until this issue is resolved, the following modules need to be opened manually in the eclipse.ini:
--add-opens java.base/java.lang=ALL-UNNAMED
--add-opens java.desktop/javax.swing=ALL-UNNAMED
--add-opens java.desktop/java.awt=ALL-UNNAMED
See https://github.com/eclipse-windowbuilder/windowbuilder/issues/1027
> Put call to exportAllModulesToAllModules() in try-catch block

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/ClassLoaderLocalMap.java
- org.eclipse.wb.rcp/plugin.xml
- org.eclipse.wb.swing/plugin.xml
The methods used to hack a custom map into the class-loader won't work anymore, unless the java.base/java.lang module is explicitly opened. The ClassLoaderLocalMap has instead been refactored into a normal map, which is bound to the lifecycle of the project class-loader.
Contributes to:
https://github.com/eclipse-windowbuilder/windowbuilder/issues/764
> Refactor class-loader hack for property cache

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/eval/evaluators/InvocationEvaluator.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/JavaInfoUtils.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/creation/ExposedPropertyCreationSupport.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/accessor/SetterAccessor.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/PolicyUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/model/broadcast/BroadcastSupport.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/ReflectionUtils.java
Convert the Methods to MethodHandles and then use the new reflection API. The methods are called as if within the declaring class.
Contributes to:
> Avoid usage of setAccessible() for methods

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/ReflectionUtils.java
This check makes sure that we only create a "private" lookup for the given class if the package has been explicitly opened for us. Otherwise an IllegalAccessException is thrown, which obscures the exceptions being thrown at other places that still access the methods directly.
> Add accessibility check to ReflectionUtils class

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/BorderLayoutInfo.java
The getChild(String,boolean) is private and can't be accessed without opening the Swing module. Use the public getLayoutComponent(String) method instead.
Contributes to
> Don't use reflection to get component within a BorderLayout

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/editor/DatePropertyEditor.java
The private "fastTime" field can't be accessed without opening the java.base module. Use the public getTime() method instead.
Contributes to
> Don't use reflection when getting the Date time

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java
This avoids the IllegalAccessException thrown when processing the package-private BoxLayout constructor and is also redundant, as the necessary changes are also done by the ReflectionUtils class.
Contributes to
> Don't call setAccessible() on the component constructors.

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/gbl/AbstractGridBagLayoutInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/gbl/GridBagConstraintsInfo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/gbl/GridBagLayoutTest.java
The protected lookupConstraints(Component) method returns a mutable instance of the GridBagConstraints, as opposed to the copy returned by the public getConstraints(Component) method.
And instead of the package-private fields describing the attributes of the grid constraints, their public counterparts should be used.
Contributes to
> Don't use reflection to get the GridBagConstraints

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/CustomizeTest.java
The protected firePropertyChange() method in the customizer is called reflectively. Because the method is declared by java.awt.Component, this will throw an exception and thus causing the test to get stuck.
Contributes to
> Make "firePropertyChange()" public in CustomizeTest

- org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite.java
- org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite2.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/property/BorderPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/tests/DesignerTestCase.java
The SWT_AWT bridge is explicitly disposed in the dispose() method, so there is no point to also call it via a dedicated  listeners. Depending on the order in which the listeners are notified, disposing the AWT frame twice may cause an SWT exception on e.g. Windows.
Note: While this issue has always existed, it only shows up now because the order in which the frame is disposed has been changed through https://github.com/eclipse-windowbuilder/windowbuilder/commit/9dd68c7a2dc08e664421a05a4d39df5fbfaf1ad6.
Closes https://github.com/eclipse-windowbuilder/windowbuilder/issues/1049
>  Remove redundant dispose listener in EmbeddedSwingComposite 

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/reflect/ProjectClassLoader.java
- org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/parser/BindingContextClassLoaderInitializer.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/util/ActivatorGetImagesByteCodeProcessor.java
The protected defineClass() method of the base class-loader can't be accessed via reflection, without explicitly opening the java.base module. Instead, it should be called via a public accessor in the ProjectClassLoader.
Contributes to
> Add public "defineClass" method to ProjectClassLoader

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/edit/EditableSource.java
The fix accidentally removed a check that would prevent the key to be changed to an invalid value. Even with this check added back, the user can still use the original translation as key.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=502397
> Bug 502397 - Provide alternative name generation for NLS keys
> Partially revert fix for Bug 502397

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/ui/TableTextCellEditor.java
The focus listener for the cell editor can be explicitly disabled by overriding the dependsOnExternalFocusListener() method since almost two decades, rendering this workaround obsolete.
Moreover, this workaround causes the cell editor to be opened in a separate window, which is why it is no longer desirable.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=58777
> [Viewers] add API to not deactivate CellEditor on FocusLost
> Remove workaround for Bug 58777

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/reflect/ReflectionUtilsTest.java
The internal fields and methods of JDK classes can only be accessed when the corresponding modules are open. This is beyond the scope of those tests and therefore mock classes should be used instead.
Contributes to
> Refactor ReflectionUtilsTests to avoid native Java classes

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/LafInfo.java
Delegate the task of creating the LookAndFeel instances to the UIManager class, to avoid the IllegalAccessException thrown for the native LAFs.
> Refactor LafInfo to avoid direct creation of LookAndFeel instance

- .github/workflows/maven.yaml
- .mvn/maven.config
The changes to the maven.yaml file are due to
https://github.com/eclipse-tycho/tycho/issues/4526
> Add Java 24 to GitHub workflow

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/DesignerPlugin.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/EnvironmentUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/ReflectionUtils.java
- org.eclipse.wb.tests/pom.xml
This removes the changes done to the ReflectionUtils class that were made to solve the IllegalAccessException thrown when BurningWave is disabled (primarily the use of MethodHandles and the FieldUtils class) and simply tries to set the "accessible" flag via trySetAcccessible().
Furthermore, BurningWave can now be disabled at launch via a system property, which is enabled by default and explicitly disabled for the tests.
Contributes to
> Finalize changes to be compatible with Java 24

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/ui/SourceComposite.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/UiUtils.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/AbstractDialogTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/AbstractNlsUiTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/ContributionItemTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/SourceCompositeTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/utils/SWTBotCTableCombo.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/utils/SWTBotEditableSource.java
This adapts the SourceCompositeTest to be executed via SWTBot. Note that for the "test_contextMenu_removeLocale" test, the SourceComposite class also needs to be adapted.
The current implementation opens a context menu based on the cell on which the user is clicked. To determine the cell, the current location of the mouse cursor is used. Because this isn't something that can be simulated, the location is now stored via the MouseDown event.
> Repair and execute SourceCompositeTest

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/EditableSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/AbstractDialogTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/AbstractNlsUiTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/ContributionItemTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/NewSourceDialogTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/NlsDialogTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/PropertiesCompositeTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/utils/SWTBotExternalizeDropDownButton.java
Those tests were previously disabled because they caused a deadlock while opening a modal dialog. By integrating SWTBot into our own UiContext class, we can avoid this problem.
> Repair and restore NLS JUnit tests

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/PluginPalettePreferences.java
This mimics the implementation of the default palette where the user can set separate fonts for categories and entries, as opposed to one font used for both.
> Separate category and entry font in GEF-based palette

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/tests/DesignerTestCase.java
The test may throw a NullPointerException if no matching type is found or if the resolution took too long. Increase timeout from 5s to 30s to account for a slower Jenkins node.
> Try to stabilize failing "Open Type" tests

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/FigureCanvas.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/RootFigureTest.java
This workaround was added in the early stages of the Draw2D/GEF migration in order to delegate the events from the Draw2D figure canvas to the WindowBuilder figure canvas.
With 0b78dc1d4839671f77d679233013a6cccc1194a0, this workaround should no longer be necessary, as now both Draw2D and WindowBuilder figures are stored in the same list.
Contributes to
https://github.com/eclipse-windowbuilder/windowbuilder/issues/1073
> [Draw2D] Remove deprecated update manager in RootFigure

- org.eclipse.wb.swing/templates/JFrame_advanced.jvt
Due to 280f8aa3282dce10f92e7d2cbe7077071aa11836, the default layout must now be initialized AFTER the content pane has been updated.
Closes https://github.com/eclipse-windowbuilder/windowbuilder/issues/1103
> Correct initialization of default layout in advanced JFrame template

- org.eclipse.wb.tests/pom.xml
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/tests/DesignerTestCase.java
On slower systems, the widgets might not show up in time, leading to sporadic test failures.
> Increase SWTBot timeout from 5s to 30s

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/PaletteFigure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/CustomTooltipManager.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
The CustomToolTipManager is only used in the context of palette figures and should therefore not be part of the generic Draw2D Figure.
> [Draw2D] Extract custom tool-tip handling from Draw2D Figure

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/EventManager.java
- org.eclipse.wb.rcp/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/forms/layout/grid/header/edit/DimensionHeaderEditPart.java
- org.eclipse.wb.swing.FormLayout/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/edit/DimensionHeaderEditPart.java
- org.eclipse.wb.swing.MigLayout/META-INF/MANIFEST.MF
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/edit/ColumnHeaderEditPart.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/edit/RowHeaderEditPart.java
- org.eclipse.wb.swt/META-INF/MANIFEST.MF
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormHeaderEditPart.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/grid/header/edit/DimensionHeaderEditPart.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/draw2d/FigureTest.java
By wrapping the tool-tip string in a Label, it is possible to use the setToolTip() method specified by the IFigure interface, thus avoiding an additional setToolTipText() method.
This Label then needs to be unwrapped in our EventManager, as figures are not yet supported here, until the manager has been harmonized with the SWTEventDispatcher.
The tool-tip handling has also been improved so that it is only shown for non-empty strings.
> [Draw2D] Harmonize tool-tip handling of WindowBuilder figures

- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/RootEditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/RootEditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/TreeViewer.java
The layer should be accessed from the RootEditPart, not the EditPartViewer. This requires the root edit part to implement the LayerManager interface and to use the LayerManager.ID as model, to become visible to the LayerManager.Helper class.
> [GEF] RootEditPart should implement the LayerManager interface

- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/EditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/tree/TreeEditPart.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/tree/policies/LayoutEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/layout/LayoutPolicyUtils.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/layout/grid/AbstractGridSelectionEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/MenuObjectEditPart.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/layout/absolute/AbsoluteComplexSelectionEditPolicy.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/gef/EditPartsContentProvider.java
- org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupSelectionEditPolicy2.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/part/widgets/DialogEditPart.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/MigLayoutEditPolicy.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/AnchorFiguresClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/grid/GridLayoutEditPolicy.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/ViewFormGefTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuComplexTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/menu/MenuPopupSimpleTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/EditPartTest.java
At some point, the GraphicalEditPart should implement the GEF interface with the same name. For this, the getChildren() method needs to be overloaded to return a list of GraphicalEditParts, which is not possible when the method already returns a list of WindowBuilder EditParts.
> [GEF] Avoid overloading of getChildren() method in EditPart

- target-platform/wb-2024-06.target
The nightly build raised the minimum Eclipse version to 2024-09, conflicting with the 2024-06 target platform.
> Use 3.24.0 release repository in target platform

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/tools/TabOrderTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/AbstractCreationTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/DragEditPartTracker.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/SelectEditPartTracker.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/TargetingTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/Tool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/MarqueeSelectionTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/ResizeTracker.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/SelectionTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/tools/DoubleClickEditPartTracker.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormHeaderLayoutEditPolicy.java
The getLocation() and getStartLocation() defined by the GEF class describe the relative location, not the absolute locations. To avoid any confusion, our methods should be called getAbsoluteLocation() and getAbsoluteStartLocation().
Note: In the future we should also migrate to relative coordinates.
> [GEF] Rename getLocation() and getStartLocation() in Tool

- org.eclipse.wb.tests/pom.xml
Increase timeout for SWTBot test to 60s in case the dialog takes a REALLY long time to show up.
> Try to stabilize MigLayoutConstraintsTest

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Layer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/handles/Handle.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/GraphicalRobot.java
This replaces the TargetFigureFindVisitor used in the findTargetHandle() method with call to findFigureAt(), which is provided by Draw2D. A custom filter is used to restrict the search to only accept Handles and to only look in the specified layer.
> [GEF] Calculate target handle using findFigureAt()

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/tools/TabOrderTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/IEditPartViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/TargetingTool.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/AbstractEditPartViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/TreeViewer.java
- org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/dnd/TreeDropListener.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/EmptyEditPartViewer.java
This renames the findTargetEditPart() to findObjectAtExcluding() to match the signature of the corresponding GEF method.
> [GEF] Harmonize findTargetEditPart method

- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
The same functionality is already provided by the findFigureAt() method defined by the Draw2D figures.
> [GEF] Avoid usage of TargetFigureFindVisitor in Designer palette

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/binding/DesignerMethodBinding.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/binding/DesignerPackageBinding.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/binding/DesignerTypeBinding.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/BindingsTest.java
Whenever a new method is added to the IMethodBinding, IPackageBinding or the ITypeBinding, the Designer implementation must be either implemented properly or throw an IllegalArgumentException().
Instead, those methods have been implemented by returning a default value, which brings the risk of diverging from the value of the underlying binding and thus leading to inconsistent behavior.
The affected methods have been adapted to take this expected behavior into consideration and for trivial cases, been correctly implemented.
Affected commits:
- cf88ae1c0c0837c7e33868bfdc06aebe2a787219
- 6912838e8f92e2033f9cd26a7b0269a662c234b2
- 6648a1ca4e007c08f2645d44bdcbb719e717ca64
- a6af2a248562552c6fd3394f35dd81a666842e1f
- 9e522234c54ec85d55288cea11a5c8e6766fcc4d
- …
> Reactivate BindingsTest and adapt Bindings classes to expected behavior

- .github/workflows/maven.yaml
This tool should only be executed when there are actual dependency changes. For the sake of security, the tool is now only executed when changes are done to the master and optionally on a PR, but only if the "dash-license" label is set.
Closes https://github.com/eclipse-windowbuilder/windowbuilder/issues/1125
> Restrict execution of dash-license tool

- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/TestProject.java
This is a follow-up to 7e26260d821b085e99d43fdf7d690c5ad5ddcd22. In case the src folder already exist, it might also still be part of the project class-path. If we try to add it again, this then causes a CoreException.
> Try to fix sporadic "Build path contains duplicate entry" exception

- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/edit/ColumnHeaderEditPart.java
- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/edit/RowHeaderEditPart.java
- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/selection/DimensionSelectionEditPolicy.java
- org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/selection/ResizeHintFigure.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/edit/ColumnHeaderEditPart.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/edit/RowHeaderEditPart.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/selection/DimensionSelectionEditPolicy.java
- org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/selection/ResizeHintFigure.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/JTabbedPaneTabEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxGlueEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxGlueHorizontalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxGlueVerticalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxRigidAreaEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxStrutHorizontalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxStrutVerticalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/component/box/StrutSelectionEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/gbl/header/edit/ColumnHeaderEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/gbl/header/edit/RowHeaderEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/gbl/header/selection/DimensionSelectionEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/menu/MenuBarDropLayoutEditPolicy.java
Update all fields and methods to use IFigure when possible.
> [GEF] Cleanup usage of WindowBuilder Figure in Swing Components

- org.eclipse.wb.core.databinding/META-INF/MANIFEST.MF
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/UiUtils.java
- org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/editor/contentproviders/CheckboxTreeViewerWrapper.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/editor/palette/DesignerPalette.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/binding/DesignerTypeBinding.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/core/SubtypesScope.java
- org.eclipse.wb.core/src/org/eclipse/wb/core/controls/test/PaletteTest.java
The methods need to be implemented because they are specified by the interface. Mark them as deprecated to avoid the resulting deprecation warning.
> Add missing `@Deprecated` annotations

- org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxGlueEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxGlueHorizontalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxGlueVerticalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxRigidAreaEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxStrutHorizontalEditPart.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/box/BoxStrutVerticalEditPart.java
There is no benefit in using our "Designer" figures, outside of dealing with relative instead of absolute coordinates.
This adapts the following edit parts:
- Horizontal Strut
- Vertical Strut
- Horizontal Glue
- Vertical Glue
- Rigid Area
- Glue
> Refactor Box edit-parts to use plain Draw2D Figures

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/GenericPropertyComposite.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/util/factory/FactoryActionsSupport.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/other/ArrayTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/ObjectInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/creation/ConstructorCreationSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/editor/StaticFieldPropertyEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/editor/StringsAddPropertyTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/AstEditorTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/ast/AstNodeUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/util/jdt/core/CodeUtilsTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/DesignerEditorTestCase.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/AbstractButtonTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/JListTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/layout/FormLayout/FormLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/layouts/AbsoluteLayoutTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/utils/StringUtilitiesTest.java
The add() method has been replaced with an insert() method. For the isEquals() method, one should use Objects.deepEquals(). However, those are only used in tests where one can simply use assertArrayEquals() instead.
> Remove usage of deprecated ArrayUtils methods

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/model/LocaleInfo.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/model/LocalePartInfos.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/ui/ChooseLocaleDialog.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/StandardConvertersTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/BundleInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/EditableSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/LocaleInfoTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/NlsSupportTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/FlagRepositoryTest.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/LocaleUtilsTest.java
The "new Locale(...)" constructor has been deprecated with Java 20 and replaced by the static "Locale.of(...)" factory. Given that WindowBuilder already requires Java 21, there is no benefit to keep using the constructor.
> Avoid usage of deprecated Locale constructor

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/reflect/CompositeClassLoader.java
The ClassLoader.getPackage(..) method has been deprecated with Java 9. Overriding a deprecated method produces a warning, unless it is also marked as deprecated.
> Mark CompositeClassLoader.getPackage(...) as deprecated

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/errors/ExceptionComposite.java
- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/errors/WarningComposite.java
With https://github.com/eclipse-windowbuilder/windowbuilder/pull/156, a new mode was added that supresses e.g. the buttons generated in the error dialog. This mode is activated via a preference, but can't be done within the UI. Meaning that those buttons are never visible to the user and thus make error reporting more difficult.
Given that this was added as a new functionality, the mode needs to be opt-in, rather than opt-out.
> Disable "Basic UI" mode by default

- org.eclipse.wb.doc.user/html-src/accessibility.asciidoc
- org.eclipse.wb.doc.user/html-src/error_reporting.asciidoc
- org.eclipse.wb.doc.user/html-src/faq.asciidoc
- org.eclipse.wb.doc.user/html-src/faq_swing.asciidoc
- org.eclipse.wb.doc.user/html-src/index.asciidoc
- org.eclipse.wb.doc.user/html-src/index_swing.asciidoc
- org.eclipse.wb.doc.user/html-src/quick_start.asciidoc
- org.eclipse.wb.doc.user/html-src/quick_start_swing.asciidoc
- org.eclipse.wb.doc.user/html-src/tipsandtricks.asciidoc
This fixes all broken links in the AsciiDoc files that don't belong to any specific components and makes them viewable from the GitHub web-page.
> Cleanup root AsciiDoc files

- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/core/CodeUtils.java
- org.eclipse.wb.rcp.databinding.emf/META-INF/MANIFEST.MF
- org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/PropertiesSupport.java
This method has been moved to the IOrdinaryClassFile interface. For all instances where we need to fetch the type, the IClassFile interface has been replaced with this new interface.
> Avoid usage of deprecated getType() method of IClassFile interface

- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/AnchorFiguresClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicy.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicyClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormSelectionEditPolicyClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormUtils.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/FormLayoutInfoImplClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/LayoutAssistantPage.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/LayoutAssistantPageClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/actions/AnchorActionsClassic.java
- org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/grid/actions/SelectionActionsSupport.java
This warning is produced because the selection is a list of ObjectInfos is compared with an IObjectInfo. To solve this warning, adapt the generic type of the implementing classes to work with the correct type.
> Fix: "Unlikely Argument: ControlInfo" warning in LayoutAssistant

- org.eclipse.wb.doc.user/html-src/userinterface/component_tree.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/context_menu.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/design_view.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/index.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/palette.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/palette_context_menu.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/palette_manager.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_color.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_font.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_image.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_inset.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_point.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_rectangle.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_string.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_string_array.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_editor_taborder.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_pane.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/property_pane_context_menu.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/source_view.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/structure_view.asciidoc
- org.eclipse.wb.doc.user/html-src/userinterface/toolbar.asciidoc
This adapts the links to other pages and images so that they are properly rendered on GitHub.
> Cleanup "user interface" doc pages

- org.eclipse.wb.doc.user/html-src/whatsnew/v122.asciidoc
- org.eclipse.wb.doc.user/toc.xml
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/Activator.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/menu/MenuBarDropLayoutEditPolicy.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/menu/MenuDropPolicyConfigurator.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/ModelMessages.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/ModelMessages.properties
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/AppletInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/menu/JMenuBarInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingScreenshotMaker.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/wizards/applet/NewJAppletWizard.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/wizards/applet/NewJAppletWizardPage.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/AppletTest.java
This formally deprecates the support for java.applet.Applet and javax.swing.JApplet in WindowBuilder. When such a container is used, a "Deprecated" label will be shown in the components tree, in addition to the deprecation warnings already generated by JDT.
All internal references (excluding the embedded previews) and imports have been removed and where necessary replaced by their fully qualified names.
In places where we check whether a container is an instance of such an Applet, the class is dynamically loaded. If the class can't be found, those check silently fail, rather than causing runtime errors.
Closes https://github.com/eclipse-windowbuilder/windowbuilder/issues/383
> Deprecate support for Applet/JApplet API #383

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/LafInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/laf/LafCanvas.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/laf/LafPreferencePage.java
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/laf/LookAndFeelTest.java
The LookAndFeel is no longer set in the SWT UI thread. More specifically, it is set before the Swing preview is created and afterwards restored.
All of those updates are done asynchronously, so this should greatly reduce the change of a deadlock due to both threads waiting for one another.
> Move setting of LookAndFeel to AWT event thread

- .github/workflows/maven.yaml
- .github/workflows/unit-tests.yml
Test results are not published properly due to an "There is no pull
request for commit <...>" error, indicating a problem with visibility
and or accessability...
> Investigate missing test-result reports

- org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite.java
See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4982522
> The problem is that Swing components (or any lightweight) will not
> receive mouse events, if they are added directly to the Windows
> embedded frame (WEmbeddedFrame). This problem only happens on Windows,
> and it is possible to work around it by adding a java.awt.Panel
> between them.
The original solution was to choose a JApplet. But as the bug says, a JPanel can be used instead.
> Replace deprecated JApplet with JRootPane.

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/Messages.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/laf/LafPreferencePage.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/messages.properties
When no preview is selected, an empty group is shown. In such a case, a label should be created, telling the user to select a LaF.
> Add default message if no LAS is selected

- org.eclipse.wb.swing/META-INF/MANIFEST.MF
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/LafSupport.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/LafInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/LafValue.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/PluginLafInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/SeparatorLafInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/laf/model/UserDefinedLafInfo.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/SwingRealm.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/preferences/laf/LafCanvas.java
Access to the Swing objects must be done from the AWT event dispatcher thread (aka the Swing UI thread). Rather than explicitly checking whether any method is called from this thread via e.g. the EventQueue, we can take advantage of the "Realm" concept provided by the Eclipse.
The LookAndFeel is stored within an ObservableValue. The realm of this value is the Swing UI thread. Modifying this value from any other thread is guaranteed to throw an exception.
> Encapsulate the Swing LookAndFeel using an ObservableValue

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/BooleanField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/ColorField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/IntegerField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/TextField.java
The setValue() of the BooleanField, ColorField, IntegerField and TextField don't throw a checked exception, so there is no purpose for the signature to contain "throws Exception".
> Remove checked exception from Border accessors

- org.eclipse.wb.core.java/src/org/eclipse/wb/core/eval/ExecutionFlowUtils.java
- org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/eval/ExecutionFlowProvider.java
- org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/parser/RcpExecutionFlowProvider.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/parser/SwingExecutionFlowProvider.java
- org.eclipse.wb.tests/META-INF/MANIFEST.MF
- org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/eval/ExecutionFlowUtilsTest.java
We already skip anonymous classes outside of a few exceptions (e.g. EventQueue.invokeLater(Runnable)). Given that Java allows the Runnable to be implemented as both an anonymous class and a lambda expression, WindowBuilder needs to be extended to support both variants.
> Don't traverse lambda expressions unless necessary

- org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/execution/ExecutionUtils.java
This method should return a CompletableFuture, rather than a void, so that additional tasks can easily be chained via the returned object.
> ExecutionUtils.runLogLater() should return a CompletableFuture

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/utils/SwingUtils.java
Similar to b7e73b02c56421f1f78964489792920cae3bedc3, this method should be adapted to return a CompletableFuture, rather than void.
> SwingUtils.runLogLater() should return a CompletableFuture

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/BooleanField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/ColorField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/ComboField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/IntegerField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/RadioField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/TextField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/BevelBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/DefaultBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/EmptyBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/EtchedBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/LineBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/MatteBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/NoBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/SoftBevelBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/SwingBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/TitledBorderComposite.java
The signature of the abstract base classes allows sub-classes to throw a generic exception. However, the implementations should only keep it in their signatures if they are able to fail.
Otherwise calling methods of those sub-classes need to be wrapped in try-catch blocks for no reason.
> The getSource() methods in the BorderDialog shouldn't throw exceptions

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/BevelBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/EmptyBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/EtchedBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/LineBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/MatteBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/SoftBevelBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/SwingBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/TitledBorderComposite.java
The fields for the Border composite pages that describe primitive types should be initialized in the constructor. Otherwise the code generation converts them to "null", leading to compilation errors.
This is currently avoid by iterating over all pages and calling setBorder(...), causing an unnecessary overhead.
> Move initialization of Border dialog fields to constructor

- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/fields/BorderField.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/AbstractBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/BevelBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/CompoundBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/EmptyBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/EtchedBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/LineBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/MatteBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/SoftBevelBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/SwingBorderComposite.java
- org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/border/pages/TitledBorderComposite.java
Rather than iterating over a list of all composite classes, define a simple lookup-table. In addition to being faster, it also avoids having two maintain two lists of composites; One for the BorderField and one for the BorderDialog.
> Simplify calculation of compatible border composite in BorderField
