eclipse-windowbuilder/windowbuilder

org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/ObserveType.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/model/forms/layout/table/TableWrapLayoutConverter.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/grid/GridLayoutConverter.java
I've removed 2 unnecessary imports (org.eclipse.jdt.internal.core.util.ComponentInfo) have been added and I also change a call to the method "List.of()" which is not available in Java 8.
=> Fix Compilation Errors

org.eclipse.wb.rcp.doc.user/html/wizards/rcp/viewpart.html, org.eclipse.wb.rcp/templates/forms/ViewPart.jvt, org.eclipse.wb.rcp/templates/rcp/ViewPart.jvt
Update the templates because initializeToolbar() causes a displaying problem on the "Design" tab
=> Bug 552210 - Design tab won't be drawn for ViewPart

org.eclipse.wb.core.feature_feature/feature.properties, org.eclipse.wb.core.java.feature_feature/feature.properties, org.eclipse.wb.core.ui.feature_feature/feature.properties, org.eclipse.wb.core.xml.feature_feature/feature.properties, org.eclipse.wb.doc.user.feature_feature/feature.properties, org.eclipse.wb.layout.group.feature_feature/feature.properties, org.eclipse.wb.rcp.SWT_AWT_support_feature/feature.properties, org.eclipse.wb.rcp.doc.user.feature_feature/feature.properties, org.eclipse.wb.rcp.feature_feature/feature.properties, org.eclipse.wb.swing.doc.user.feature_feature/feature.properties, org.eclipse.wb.swing.feature_feature/feature.properties, org.eclipse.wb.swt.feature_feature/feature.properties, org.eclipse.wb.xwt.feature_feature/feature.properties
Update feature names and copyright
=> Bug 461845 - Window Builder is not useable

org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/DesignerPluginTest.java
=> Security manager removed from WB code so lets remove it also from the tests

org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/property/editor/color/ColorPropertyEditor.java
Reformat of Color Property Editor
=> Applying save action to reformat

.github/workflows/maven.yaml
Show test results in PR.
Ref #42
=> Revive WB Tests

org.eclipse.wb.tests/pom.xml, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/ContentDescriberTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/JavaPropertiesToolBarContributorTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/TopSelectionEditPolicyTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/UndoManagerTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/action/CopyActionTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/action/CutActionTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/action/SwitchActionTest.java
Trying to run some tests during WB build.
Ref #42
=> Revive org.eclipse.wb.tests.designer.editor.EditorTests Tests

org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/RcpDescriptionVersionsProviderFactory.java
=> Extend SWT version check for future versions

org.eclipse.wb.discovery.core/.classpath, org.eclipse.wb.discovery.core/.settings/org.eclipse.jdt.core.prefs, org.eclipse.wb.discovery.core/META-INF/MANIFEST.MF, org.eclipse.wb.discovery.ui/.classpath, org.eclipse.wb.discovery.ui/.settings/org.eclipse.jdt.core.prefs, org.eclipse.wb.discovery.ui/META-INF/MANIFEST.MF
=> Update org.eclipse.wb.discovery to Java 11

org.eclipse.wb.layout.group/.classpath, org.eclipse.wb.layout.group/.settings/org.eclipse.jdt.core.prefs, org.eclipse.wb.layout.group/META-INF/MANIFEST.MF
=> Update org.eclipse.wb.layout.group to Java 11

org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/layout/LayoutInfo.java
When selecting the Restore default value option on the Layout property
the property would disappear form the Properties view and could only be
viewed again when closing and opening the editor again or undoing the
default value setting.
see "Restore default value" on Layout property causes the Layout
property to disappear #93
=> Fixing the Layout Properties Restore default value bug

org.eclipse.wb.core.databinding.xml/src/org/eclipse/wb/internal/core/databinding/xml/Activator.java, org.eclipse.wb.core.databinding.xml/src/org/eclipse/wb/internal/core/databinding/xml/model/SynchronizeManager.java, org.eclipse.wb.core.databinding.xml/src/org/eclipse/wb/internal/core/databinding/xml/parser/DatabindingRootProcessor.java, org.eclipse.wb.core.databinding.xml/src/org/eclipse/wb/internal/core/databinding/xml/ui/AbstracXmlObjectPropertiesManager.java, org.eclipse.wb.core.databinding.xml/src/org/eclipse/wb/internal/core/databinding/xml/ui/BindingXmlPage.java
=> Code cleanup run to add missing annotations org.eclipse.wb.databinding.xml

org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/FormLayoutEditPolicy.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/FormSelectionEditPolicy.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/LayoutEditPolicyFactory.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/edit/ColumnHeaderEditPart.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/edit/RowHeaderEditPart.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/gef/header/selection/DimensionSelectionEditPolicy.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/FormDimensionUtils.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/FormLayoutInfo.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/FormLayoutSurroundProcessor.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/ui/ColumnsDialog.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/ui/ConstantSizeComposite.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/ui/DimensionEditDialog.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/ui/DimensionsDialog.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/model/ui/RowsDialog.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/palette/DefaultComponentFactoryCreateLabelEntryInfo.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/palette/DefaultComponentFactoryCreateTitleEntryInfo.java, org.eclipse.wb.swing.FormLayout/src/org/eclipse/wb/internal/swing/FormLayout/parser/DefaultComponentFactoryCreationSupport.java
=> Code cleanup run to add missing annotations org.eclipse.wb.swing.FormLayout

org.eclipse.wb.rcp.swing2swt/src/org/eclipse/wb/internal/rcp/swing2swt/gef/LayoutEditPolicyFactory.java, org.eclipse.wb.rcp.swing2swt/src/org/eclipse/wb/internal/rcp/swing2swt/layout/BorderLayoutInfo.java
=> Code cleanup run to add missing annotations org.eclipse.wb.rcp.swing2swt

org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/DatabindingFactory.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/DatabindingsProvider.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/DesignPageFactory.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/AttributeDocumentEditor.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/BindingInfo.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/ElementDocumentEditor.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/ObserveTypeContainer.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/TreeViewerBindingInfo.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/ViewerBindingInfo.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/widgets/WidgetBindableInfo.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/model/widgets/XmlObjectReferenceProvider.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/parser/DatabindingParser.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/ui/contentproviders/ConverterUiContentProvider.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/ui/contentproviders/ModeContentProvider.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/ui/contentproviders/TriggerContentProvider.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/ui/contentproviders/ValidationUiContentProvider.java, org.eclipse.wb.rcp.databinding.xwt/src/org/eclipse/wb/internal/rcp/databinding/xwt/ui/providers/BindingLabelProvider.java
=> Code cleanup run to add missing annotations org.eclipse.wb.rcp.databinding.xwt

org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/AutomaticWizardStub.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/CreatorManager.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/EmfObserveTypeContainer.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/GlobalObservableFactory.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/DirectPropertyBindableInfo.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/EObjectBindableInfo.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/EObjectObservePresentation.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/EPropertyBindableInfo.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/HierarchySupport.java, org.eclipse.wb.rcp.databinding.emf/src/org/eclipse/wb/internal/rcp/databinding/emf/model/bindables/PropertiesSupport.java
=> Code cleanup run to add missing annotations org.eclipse.wb.rcp.databinding.emf

org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutAligner.java, org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutDesigner.java, org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutModel.java, org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/LayoutUtils.java, org.eclipse.wb.layout.group/netbeans-src/org/netbeans/modules/form/layoutdesign/support/SwingLayoutCodeGenerator.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/FeedbacksDrawer.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupLayoutEditPolicy2.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupSelectionEditPolicy2.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/GroupLayoutParserVisitor2.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/GroupLayoutSupport.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/assistant/GroupLayoutAlignmentPage.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/assistant/GroupLayoutSpacesPage.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/model/assistant/LayoutAssistantSupport.java
=> Code cleanup run to add missing annotations org.eclipse.wb.layout.group

org.eclipse.wb.dev/src/org/eclipse/wb/internal/dev/builder/ComponentDescriptionValidatorHandler.java, org.eclipse.wb.dev/src/org/eclipse/wb/internal/dev/builder/MetaDataModificationHandler.java, org.eclipse.wb.dev/src/org/eclipse/wb/internal/dev/builder/WbNature.java
=> Code cleanup run to add missing annotations org.eclipse.wb.dev

org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/LayoutsPreferencePage.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/MainPreferencePage.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/ParsingPreferencePage.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/PreferencePageFactory.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/wizards/actions/AbstractOpenWizardAction.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/wizards/actions/NewDesignerTypeDropDownAction.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/wizards/palette/NewProjectPalettePage.java, org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/wizards/palette/NewProjectPaletteWizard.java
=> Code cleanup run to add missing annotations org.eclipse.wb.core.ui

.mvn/extensions.xml, pom.xml
Tycho released 2.7.2 and we want to stay current.
=> Tycho update to 2.7.2

org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/converter/ByteObjectConverter.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/converter/DoubleObjectConverter.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/converter/IntegerObjectConverter.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/converter/LongObjectConverter.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/property/converter/ShortObjectConverter.java
=> Fixed warning on deprecated Number-Object constructor use since JDK9

.mvn/extensions.xml, pom.xml
Always a good choice to follow latest Tycho release.
=> Update to Tycho 2.7.3

org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/WindowBuilderTests.java
SwingTests included in the Windowbuilder Test Suite
=> Include SwingTests in the POM file

org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/EditSelection.java, org.eclipse.wb.core.databinding/src/org/eclipse/wb/internal/core/databinding/ui/editor/contentproviders/ChooseClassAndPropertiesUiContentProvider.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/generation/GenerationSettings.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/ObjectPathHelper.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/policy/snapping/PlacementsSupport.java, org.eclipse.wb.layout.group/src/org/eclipse/wb/internal/layout/group/gef/GroupLayoutEditPolicy2.java, org.eclipse.wb.rcp.databinding/src/org/eclipse/wb/internal/rcp/databinding/wizards/autobindings/SwtDatabindingProvider.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicyClassic.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/layout/form/FormDataInfo.java
https://github.com/eclipse/windowbuilder/pull/253
https://github.com/eclipse/windowbuilder/pull/253 plans to update the library usage of commons collections. To avoid mixing formatting changes and real changes, the affected files are extracted into this PR.
=> Format files affected by PR 253

org.eclipse.wb.core/src/org/eclipse/wb/internal/core/DesignerPlugin.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/dialogs/ResizableDialog.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/ui/dialogs/ResizableTitleAreaDialog.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/tests/Activator.java
Instead of AbstractUIPlugin use PlatformUI directly
=> Remove deprecated API usage

target-platform/wb.target
Updating target platform to build against 2022-06 Eclipse release.
=> Building WB against latest Eclipse release

org.eclipse.wb.releng.updatesite/pom.xml, pom.xml
https://github.com/eclipse/windowbuilder/issues/302
=> tycho-gpg-plugin should only be done in the repository pom

org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/ContainerEditPart.java, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/ContainerInfo.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/part/CompositeEditPart.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/model/widgets/CompositeInfo.java
=> Issue 311 fix

org.eclipse.wb.tests/META-INF/MANIFEST.MF
Removed unused juniper api from test bundle
=> IDE setup with installer fails #324

pom.xml
=>  [SWT] Empty Design tab on Mac M1 Pro #344

org.eclipse.wb.releng.updatesite/category.xml
We are planning to remove the unmaintained and broken XWT support. As a first step, lets remove it from the update site.
=> Removes xwt support from WB update site

org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/support/CoordinateUtilsTest.java
While the shell is invisible, its coordinates are not properly updated. When attempting to calculate the shell location and client area insets, GTK returns junk coordinates to the WB. Which then results in nonsensical insets and bounds.
=> Fix calculation of shell insets in CoordinateUtilsTest

org.eclipse.wb.os.linux/src/org/eclipse/wb/internal/os/linux/OSSupportLinux.java
Those classes aren't loaded on Windows/MacOS, leading to compile errors in the workspace. This has no impact on the runtime behavior, as the LinuxOSSupport class is only available on Linux.
=> Access the interval GDK/GTK classes via reflection instead of directly.

setups/WindowBuilder.setup
=> Fix the website setup to clone from github

org.eclipse.wb.core.lib/META-INF/MANIFEST.MF
=> Remove references to deleted jars in org.eclipse.wb.core.lib

setups/WindowBuilder.setup
=> Fix the website setup to clone to remove qualification of the folder

Jenkinsfile
=> Provide a Jenkinsfile for a multi-branch pipeline build

CONTRIBUTING.md, Jenkinsfile, README.md, org.eclipse.wb.core/src/org/eclipse/wb/core/branding/DefaultBrandingDescription.java, org.eclipse.wb.doc.user/html/error_reporting.html, org.eclipse.wb.doc.user/html/support/product_support.html, org.eclipse.wb.doc.user/toc.xml, org.eclipse.wb.releng.updatesite/pom.xml, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/ExpandBarTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/rcp/model/widgets/TableGefTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/model/widgets/TableTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swt/support/CoordinateUtilsTest.java, setups/WindowBuilder.setup
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3149
=> Fix URLs to reference the eclipse-windowbuilder organization

org.eclipse.wb.core.java/plugin.properties, org.eclipse.wb.core.ui/plugin.properties, org.eclipse.wb.core.xml/plugin.properties, org.eclipse.wb.core/plugin.properties, org.eclipse.wb.rcp.databinding.emf/plugin.properties, org.eclipse.wb.rcp.databinding.xwt/plugin.properties, org.eclipse.wb.rcp.databinding/plugin.properties, org.eclipse.wb.rcp.nebula/plugin.properties, org.eclipse.wb.rcp.swing2swt/plugin.properties, org.eclipse.wb.rcp/plugin.properties, org.eclipse.wb.releng.updatesite/.gitignore, org.eclipse.wb.swing.FormLayout.lib/plugin.properties, org.eclipse.wb.swing.FormLayout/plugin.properties, org.eclipse.wb.swing.MigLayout.lib/plugin.properties, org.eclipse.wb.swing.MigLayout/plugin.properties, org.eclipse.wb.swing.databinding/plugin.properties, org.eclipse.wb.swing.java6/plugin.properties, org.eclipse.wb.swing.jsr296/plugin.properties, org.eclipse.wb.swing/plugin.properties, org.eclipse.wb.swt.widgets.baseline/plugin.properties, org.eclipse.wb.swt/plugin.properties, org.eclipse.wb.xwt/plugin.properties
=> Consistently prefix all plug-in names with WindowBuilder

org.eclipse.wb.core.lib/build.properties, org.eclipse.wb.releng.updatesite/category.xml, pom.xml
https://github.com/eclipse-windowbuilder/windowbuilder/issues/438
=> Provide source bundles and features

org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/ComponentInfo.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/JDialogTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/JInternalFrameTest.java
This reverts commit 39b287514511e1ecb7b8f32396db21e204d1463c.
=> Revert "Fix invalid bounds of Swing components on Linux"

org.eclipse.wb.core/src/org/eclipse/wb/core/controls/palette/PaletteComposite.java
Amends bfb3c0cc72d03d69cc792dbf8d9bf1710414ad80
=> Fix: NPE when creation a Font from an uninitialized FontDescriptor.

org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/creation/ThisCreationSupport.java
It may happen that inside the constructor, we create and run a separate thread. Because the method interceptor is stored in a thread-local variable, it is not available to this thread.
Instead, the interceptor is stored in an atomic variable. Note that this requires that the object creation has to be synchronized. Otherwise it might happen that an instance created in one thread is using the interceptor of another instance created in a different thread.
=> Fix: Occasional NPE when creating a mocked widget

org.eclipse.wb.core.java/META-INF/MANIFEST.MF, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/tools/TabOrderTool.java, org.eclipse.wb.core.xml/META-INF/MANIFEST.MF, org.eclipse.wb.core/META-INF/MANIFEST.MF, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/AbstractCreationTool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/DragEditPartTracker.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/ParentTargetDragEditPartTracker.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/SelectEditPartTracker.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/TargetingTool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/tools/Tool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/MarqueeSelectionTool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/ResizeTracker.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/SelectionTool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/EditDomain.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/tools/DoubleClickEditPartTracker.java, org.eclipse.wb.tests/META-INF/MANIFEST.MF
This should allow us to use this class in a pure GEF context when we continue with the GEF migration.
=> [GEF] Extend the Tools class with the downstream GEF implementation.

org.eclipse.wb.core/META-INF/MANIFEST.MF, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/EditPart.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/IEditPartFactory.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/IEditPartViewer.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/core/policies/EditPolicy.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/GraphicalEditPart.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/MarqueeSelectionTool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/tree/TreeEditPart.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/core/AbstractEditPartViewer.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/RootEditPart.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/RootEditPart.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/tree/TreeViewer.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/MenuObjectEditPart.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/SubmenuAwareEditPart.java, org.eclipse.wb.swing/META-INF/MANIFEST.MF, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/part/ContainerEditPart.java, org.eclipse.wb.swt/META-INF/MANIFEST.MF, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/part/CompositeEditPart.java, org.eclipse.wb.tests/META-INF/MANIFEST.MF, org.eclipse.wb.tests/src/org/eclipse/wb/tests/gef/EmptyEditPartViewer.java
Our own EditPart implementation now also implements the GEF interface. This is the first step in the process of updating to the latest GEF version.
=> [GEF] Extend GEF EditPart interface and resolve compile errors

RELEASE_NOTES.md
Document all known incompatibilities or breaking changes that may affect user code.
=> Create release notes for WB 1.13.0 & 1.14.0

org.eclipse.wb.core.java/META-INF/MANIFEST.MF, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/nls/bundle/StandardPropertiesAccessor.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/jdt/ui/PreferencesAdapter.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/utils/dialogfields/DialogFieldUtils.java, org.eclipse.wb.swing.java6/META-INF/MANIFEST.MF, org.eclipse.wb.swing.java6/src/org/eclipse/wb/internal/swing/java6/gef/GroupSelectionEditPolicy.java, org.eclipse.wb.swing.java6/src/org/eclipse/wb/internal/swing/java6/model/GroupLayoutInfo.java, org.eclipse.wb.swing/META-INF/MANIFEST.MF, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/gef/policy/layout/SpringSelectionEditPolicy.java, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/component/SwingInvocationEvaluatorInterceptor.java, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/models/combo/ComboBoxModelPropertyEditor.java, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/models/list/ListModelEvaluator.java, org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/model/property/editor/models/list/ListModelPropertyEditor.java, org.eclipse.wb.swt/META-INF/MANIFEST.MF, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/AbsoluteLayoutEditPolicy.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicy2.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormSelectionEditPolicy.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormSelectionEditPolicy2.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gefTree/LayoutEditPolicyFactory.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/parser/SwingParserTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/swing/model/component/JListTest.java
This should reduce the total number of warnings by ~50.
=> Fix various raw type warnings in WindowBuilder code

org.eclipse.wb.core/src-draw2d/org/eclipse/wb/draw2d/Figure.java, org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/EventManager.java, org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/FigureCanvas.java, org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/RootFigure.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/GraphicalViewer.java
Call EventDispatcher method directly instead.
=> [Draw2D] Remove setCapture() methods in Figure

org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/ComponentDescriptionHelper.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/FactoryDescriptionHelper.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ConfigurableObjectListParameterRule.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ConfigurableObjectParameterRule.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/MethodTagRule.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/ParameterTagRule.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/PublicFieldPropertiesRule.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/rules/SetClassPropertyRule.java
=> Remove usage of Digester3 in ComponentDescriptorHelper in favor of JAXB

org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/model/description/helpers/FactoryDescriptionHelper.java
The check whether a wbp-factory xml file has a proper namespace doesn't work and will always log a warning.
Use a different approach by parsing the document using W3C and then simply updating the root element, if necessary. Only then is the document passed to JAXB.
=> Fix improper warnings regarding invalid wbp-factory xml files

org.eclipse.wb.core/src-draw2d/org/eclipse/wb/internal/draw2d/FigureCanvas.java
If the update manager is changed after the canvas has been created, the scrollbar is no longer updated.
Amends 7accf5c34ada49446a8392c289683630e4797e15
=> Fix: Scrollbar are no longer shown for palette and canvas.

org.eclipse.wb.releng.updatesite/pom.xml
https://github.com/eclipse-windowbuilder/windowbuilder/issues/771
=> Use Java 21 for publishing to preserve posix permissions in site zip

org.eclipse.wb.core.ui/src/org/eclipse/wb/internal/core/preferences/LayoutsPreferencePage.java
See https://github.com/eclipse-windowbuilder/windowbuilder/issues/793
Amends b7b7c51783004b38a711ddfb8402865853bd1904
=> The selection in LayoutPreferencePage needs to be updated on new input

org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/HtmlTooltipHelper.java
A "location changing" event is fired while the tooltip is constructed on Linux (but not on Windows). Because the listener for this event disposes the tooltip shell, the browser is closed before it is completed, resulting in the tooltip never being shown.
The purpose of this listener is to close the tooltip when a hyperlink has been clicked and to open the URL in the normal web browser. It is therefore sufficient to only add this listener AFTER the tooltip has been created and made visible, therefore ignoring all intermediate events.
Fixes https://github.com/eclipse-windowbuilder/windowbuilder/issues/842
=> Fix: HTML Tooltip not show on Linux

org.eclipse.wb.doc.user/html-src/whatsnew/index.asciidoc
This extension point has been added to customize the code generation when dealing with Swing/SWT images.
=> Mention "org.eclipse.wb.core.java.imageProcessor" extension point in N&N

target-platform/wb.target
The archived p2 repository is no longer accessible.
=> Update URL to Eclipse Nebula update site

org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java
The generic getLevelIndent() method, as well as the property-info specific methods getTitleX(PropertyInfo), getTitleTextX(PropertyInfo), and isLocationState(PropertyInfo) methods have been moved from the PropertyTable to the PropertyEditPart. The latter methods also no longer expect a PropertyInfo parameter and instead use the edit-part model.
All calls to these methods have been updated to go through the edit part, as this instance is already known at that point.
The PropertyFigure has been turned into an inner class of the PropertyEditPart, to emphasize that one class can't exist without the other and to make it easier for later extraction.
=> Unify functionality related to the PropertyEditPart

org.eclipse.wb.core/src/org/eclipse/wb/internal/core/editor/structure/property/ComponentsPropertiesPage.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/PropertyTable.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/AbstractPropertyEditPart.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/NoPropertyEditPart.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/PropertyEditPart.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/PropertyEditPartFactory.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/PropertyRootEditPart.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/table/PropertyTableEditorsTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/table/PropertyTableTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/model/property/table/PropertyTableTooltipTest.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/editor/ComponentsPropertiesPageTest.java
This extracts the property edit parts from the PropertyTable class and moves them into a separate package.
=> Extract property edit parts

org.eclipse.wb.core/src/org/eclipse/wb/internal/core/model/property/table/editparts/PropertyEditPart.java
This is done in preparation to simplify the tooltip handling for both figures, as now it is possible to add listeners to each figure to handle when a tooltip should be shown and what content it should have.
=> Split PropertyFigure into TitleFigure and ValueFigure

org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/utils/ast/AnonymousTypeDeclaration.java
Avoid the call to setAccessible() to avoid issues when BurningWave isn't installed.
=> Refactor reflective loading of AnonymousTypeDeclaration

.github/workflows/maven.yaml, .github/workflows/unit-tests.yml, org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/WindowBuilderProjectExplorerBot.java, org.eclipse.wb.tests/src/org/eclipse/wb/tests/swtbot/designer/bot/WindowBuilderWorkbenchBot.java, target-platform/wb-2024-06.target
- Update to Maven 3.9.9
- Consider target platform to build against
- Add version to every action
=> Cleanup and update GitHub YAML files

target-platform/mvn/wb-mvn.target
Closes https://github.com/eclipse-windowbuilder/windowbuilder/issues/1027
=> Update Maven dependencies to their latest version

org.eclipse.wb.tests/src/org/eclipse/wb/tests/designer/core/nls/ui/SourceCompositeTest.java
This replaces the simulated key events generated by SWTBot with more stable counterparts. Instead of a "ENTER" key, the active cell editor is closed by calling "applyEditorValue" on the underlying table viewer and instead of posting the remaining key events to "Display.post()", the events are instead directly passed to the targeted widget.
Closes https://github.com/eclipse-windowbuilder/windowbuilder/issues/1096
=> Stabilize SourceCompositeTests to avoid occasional SEGFAULT

org.eclipse.wb.core.java/src/org/eclipse/wb/core/gef/policy/TabOrderContainerEditPolicy.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/part/nonvisual/NonVisualBeanEditPart.java, org.eclipse.wb.core.java/src/org/eclipse/wb/internal/core/gef/policy/OpenErrorLogEditPolicy.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/GraphicalEditPart.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/handles/Handle.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/handles/MoveHandleLocator.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/handles/SideResizeHandle.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/gef/graphical/tools/MarqueeSelectionTool.java, org.eclipse.wb.core/src-gef/org/eclipse/wb/internal/gef/graphical/RootEditPart.java, org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/PolicyUtils.java, org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/layout/grid/AbstractGridHelper.java, org.eclipse.wb.core/src/org/eclipse/wb/core/gef/policy/validator/BorderOfChildLayoutRequestValidator.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/MenuEditPart.java, org.eclipse.wb.core/src/org/eclipse/wb/internal/core/gef/part/menu/SubmenuAwareEditPart.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/part/jface/ControlDecorationEditPart.java, org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/MigLayoutSplitEditPolicy.java, org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/edit/ColumnHeaderEditPart.java, org.eclipse.wb.swing.MigLayout/src/org/eclipse/wb/internal/swing/MigLayout/gef/header/edit/RowHeaderEditPart.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormHeaderEditPart.java
Adapt the signature of all methods to exclusively work with IFigures.
=> [GEF] Generalize GraphicalEditPart to work with IFigures

org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/part/rcp/perspective/EditorAreaEditPart.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/part/rcp/perspective/shortcuts/AbstractShortcutContainerEditPart.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/forms/layout/ColumnLayoutSelectionEditPolicy.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/forms/layout/grid/header/edit/ColumnHeaderEditPart.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/forms/layout/grid/header/edit/RowHeaderEditPart.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/layout/StackLayoutNavigationFigure.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/rcp/perspective/AbstractPartSelectionEditPolicy.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/widgets/SashFormSelectionEditPolicy.java, org.eclipse.wb.rcp/src/org/eclipse/wb/internal/rcp/gef/policy/widgets/TreeTreeColumnSelectionEditPolicy.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/TableTableColumnSelectionEditPolicy.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/RowLayoutSelectionEditPolicy.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/AnchorFiguresClassic.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormHeaderEditPart.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormHeaderLayoutEditPolicy.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicy2.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormLayoutEditPolicyClassic.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/form/FormSelectionEditPolicyClassic.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/grid/header/edit/ColumnHeaderEditPart.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/layout/grid/header/edit/RowHeaderEditPart.java, org.eclipse.wb.swt/src/org/eclipse/wb/internal/swt/gef/policy/menu/MenuBarDropLayoutEditPolicy.java
Update all fields and methods to use IFigure when possible.
=> [GEF] Cleanup usage of WindowBuilder Figure in SWT/RCP Components

org.eclipse.wb.swing.databinding/src/org/eclipse/wb/internal/swing/databinding/model/bindings/VirtualParser.java
Use NumberUtils.isCreatable(...) as drop-in replacement.
=> Avoid usage of NumberUtils.isNumber(...)

org.eclipse.wb.swing/src/swingintegration/example/EmbeddedSwingComposite.java
This restores the UIDefaults for the fonts when the widget is disposed. Otherwise changes to e.g. the LookAndFeel fonts would be preserved, even when the LookAndFeel dialog has been closed.
Furthermore, disposing the Swing Frame is now done via a DisposeEvent. The dispose() method is not called recursively, so there is no guarantee that it is actually disposed.
=> Properly reset the EmbeddedSwingComposite when disposed

target-platform/mvn/wb-mvn.target
jakarta.activation-api: 2.1.3 -> 2.1.4
jakarta.xml.bind-api: 4.0.2 -> 4.0.4
=> Update Jakarta Activation/XML Bind API to their latest release
